import { PGlite } from "@electric-sql/pglite";
import { fixtureSql } from "./practice-fixtures.mjs";
export const JUDGE_VERSION = "2026-09-04.1";
const quote = (value) => `'${String(value).replaceAll("'", "''")}'`;
const json = (value) => `${quote(JSON.stringify(value))}::jsonb`;
export async function generateJudgeContent(questions) {
  const db = new PGlite();
  const statements = [
    "-- Generated by pnpm content:judge. Do not edit computed rows. Private server content only.",
    "alter table game_private.question_cases add column expected_types jsonb;",
    `create or replace function game_private.get_judge_manifest(
  requested_ruin smallint,
  requested_dataset_version text
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  manifest jsonb;
begin
  select jsonb_build_object(
    'ruin', question.ruin_id,
    'datasetVersion', question.dataset_version,
    'allowedTables', question.allowed_tables,
    'maxResultRows', question.max_result_rows,
    'statementTimeoutMs', question.statement_timeout_ms,
    'cases', (
      select jsonb_agg(
        jsonb_build_object(
          'id', test_case.case_id,
          'fixtureSchema', test_case.fixture_schema,
          'hidden', test_case.hidden,
          'comparison', test_case.comparison,
          'expectedColumns', test_case.expected_columns,
          'expectedRows', test_case.expected_rows,
          'expectedTypes', test_case.expected_types
        ) order by test_case.hidden, test_case.case_id
      )
      from game_private.question_cases as test_case
      where test_case.ruin_id = question.ruin_id
        and test_case.dataset_version = question.dataset_version
    )
  )
  into manifest
  from game_private.questions as question
  where question.ruin_id = requested_ruin
    and question.dataset_version = requested_dataset_version
    and question.enabled;

  if manifest is null then
    raise exception 'judge manifest not found' using errcode = 'P0002';
  end if;

  return manifest;
end;
$$;`,
    "-- Versioned schemas preserve the existing Ruin 06 deployment during rollout.",
    `create table game_private.question_help (
      ruin_id smallint not null, dataset_version text not null,
      title text not null, description text not null, hints jsonb not null, solution text not null,
      primary key (ruin_id, dataset_version),
      foreign key (ruin_id, dataset_version) references game_private.questions(ruin_id, dataset_version)
    );
    revoke all on game_private.question_help from public, anon, authenticated, dilli_judge_executor, dilli_judge_progress;`,
  ];
  try {
    for (const q of questions) {
      statements.push(`insert into game_private.questions (ruin_id, dataset_version, allowed_tables) values
        (${q.id}, ${quote(JUDGE_VERSION)}, ${json(q.schema.map((t) => t.name))});`);
      statements.push(`insert into game_private.question_help values
        (${q.id}, ${quote(JUDGE_VERSION)}, ${quote(q.title)}, ${quote(q.description)}, ${json(q.hints)}, ${quote(q.canonicalSolution)});`);
      for (let i = 0; i < 3; i++) {
        const suffix = ["visible", "hidden_a", "hidden_b"][i];
        const schema = `fixture_r${String(q.id).padStart(2, "0")}_v20260904_1_${suffix}`;
        const sql = fixtureSql(q, i);
        await db.exec(
          `drop schema public cascade; create schema public; ${sql}`,
        );
        const result = await db.query(q.canonicalSolution);
        const columns = result.fields.map((f) => f.name);
        const rows = result.rows.map((row) => columns.map((c) => row[c]));
        statements.push(`create schema ${schema};
revoke all on schema ${schema} from public, anon, authenticated;
set search_path = ${schema}, pg_catalog;
${sql}
reset search_path;
revoke all on all tables in schema ${schema} from public, anon, authenticated;
grant usage on schema ${schema} to dilli_judge_executor;
grant select on all tables in schema ${schema} to dilli_judge_executor;
${q.schema.map((t) => `analyze ${schema}."${t.name}";`).join("\n")}
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (${q.id}, ${quote(`${JUDGE_VERSION}-${suffix}`)}, ${quote(schema)}, ${quote(JUDGE_VERSION)}, ${i > 0}, ${quote(q.ordered ? "ordered" : "unordered")}, ${json(columns)}, ${json(rows)}, ${json(result.fields.map((f) => f.dataTypeID))});`);
      }
    }
    return statements.join("\n\n") + "\n";
  } finally {
    await db.close();
  }
}
