-- Generated by pnpm content:judge. Do not edit computed rows. Private server content only.

alter table game_private.question_cases add column expected_types jsonb;

create or replace function game_private.get_judge_manifest(
  requested_ruin smallint,
  requested_dataset_version text
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  manifest jsonb;
begin
  select jsonb_build_object(
    'ruin', question.ruin_id,
    'datasetVersion', question.dataset_version,
    'allowedTables', question.allowed_tables,
    'maxResultRows', question.max_result_rows,
    'statementTimeoutMs', question.statement_timeout_ms,
    'cases', (
      select jsonb_agg(
        jsonb_build_object(
          'id', test_case.case_id,
          'fixtureSchema', test_case.fixture_schema,
          'hidden', test_case.hidden,
          'comparison', test_case.comparison,
          'expectedColumns', test_case.expected_columns,
          'expectedRows', test_case.expected_rows,
          'expectedTypes', test_case.expected_types
        ) order by test_case.hidden, test_case.case_id
      )
      from game_private.question_cases as test_case
      where test_case.ruin_id = question.ruin_id
        and test_case.dataset_version = question.dataset_version
    )
  )
  into manifest
  from game_private.questions as question
  where question.ruin_id = requested_ruin
    and question.dataset_version = requested_dataset_version
    and question.enabled;

  if manifest is null then
    raise exception 'judge manifest not found' using errcode = 'P0002';
  end if;

  return manifest;
end;
$$;

-- Versioned schemas preserve the existing Ruin 06 deployment during rollout.

create table game_private.question_help (
      ruin_id smallint not null, dataset_version text not null,
      title text not null, description text not null, hints jsonb not null, solution text not null,
      primary key (ruin_id, dataset_version),
      foreign key (ruin_id, dataset_version) references game_private.questions(ruin_id, dataset_version)
    );
    revoke all on game_private.question_help from public, anon, authenticated, dilli_judge_executor, dilli_judge_progress;

insert into game_private.questions (ruin_id, dataset_version, allowed_tables) values
        (1, '2026-09-04.1', '["catalog_columns"]'::jsonb);

insert into game_private.question_help values
        (1, '2026-09-04.1', 'Reading the Resident Schema', 'The gate catalog lists every attribute of each entity. Return `attribute` and `data_type` for the `resident` entity, sorted by `attribute`.', '["An entity''s attributes are just the rows where `entity` matches; filter then sort."]'::jsonb, 'SELECT attribute, data_type
FROM catalog_columns
WHERE entity = ''resident''
ORDER BY attribute;');

create schema fixture_r01_v20260904_1_visible;
revoke all on schema fixture_r01_v20260904_1_visible from public, anon, authenticated;
set search_path = fixture_r01_v20260904_1_visible, pg_catalog;
CREATE TABLE "catalog_columns" ("entity" text, "attribute" text, "data_type" text, "is_key" boolean);
INSERT INTO "catalog_columns" VALUES
('resident', 'resident_id', 'integer', true),
('resident', 'name', 'text', false),
('shelter', 'capacity', 'integer', false),
('resident', 'home_id', 'integer', false),
(NULL, 'unknown', 'text', false);
reset search_path;
revoke all on all tables in schema fixture_r01_v20260904_1_visible from public, anon, authenticated;
grant usage on schema fixture_r01_v20260904_1_visible to dilli_judge_executor;
grant select on all tables in schema fixture_r01_v20260904_1_visible to dilli_judge_executor;
analyze fixture_r01_v20260904_1_visible."catalog_columns";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (1, '2026-09-04.1-visible', 'fixture_r01_v20260904_1_visible', '2026-09-04.1', false, 'ordered', '["attribute","data_type"]'::jsonb, '[["home_id","integer"],["name","text"],["resident_id","integer"]]'::jsonb, '[25,25]'::jsonb);

create schema fixture_r01_v20260904_1_hidden_a;
revoke all on schema fixture_r01_v20260904_1_hidden_a from public, anon, authenticated;
set search_path = fixture_r01_v20260904_1_hidden_a, pg_catalog;
CREATE TABLE "catalog_columns" ("entity" text, "attribute" text, "data_type" text, "is_key" boolean);
INSERT INTO "catalog_columns" VALUES
(NULL, 'unknown-1', 'text', false),
('resident', 'home_id-1', 'integer', false),
('shelter', 'capacity-1', 'integer', false),
('resident', 'name-1', 'text', false),
('resident', 'resident_id-1', 'integer', true);
reset search_path;
revoke all on all tables in schema fixture_r01_v20260904_1_hidden_a from public, anon, authenticated;
grant usage on schema fixture_r01_v20260904_1_hidden_a to dilli_judge_executor;
grant select on all tables in schema fixture_r01_v20260904_1_hidden_a to dilli_judge_executor;
analyze fixture_r01_v20260904_1_hidden_a."catalog_columns";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (1, '2026-09-04.1-hidden_a', 'fixture_r01_v20260904_1_hidden_a', '2026-09-04.1', true, 'ordered', '["attribute","data_type"]'::jsonb, '[["home_id-1","integer"],["name-1","text"],["resident_id-1","integer"]]'::jsonb, '[25,25]'::jsonb);

create schema fixture_r01_v20260904_1_hidden_b;
revoke all on schema fixture_r01_v20260904_1_hidden_b from public, anon, authenticated;
set search_path = fixture_r01_v20260904_1_hidden_b, pg_catalog;
CREATE TABLE "catalog_columns" ("entity" text, "attribute" text, "data_type" text, "is_key" boolean);
INSERT INTO "catalog_columns" VALUES
(NULL, 'unknown-2', 'text', false),
('shelter', 'capacity-2', 'integer', false),
('resident', 'name-2', 'text', false),
('resident', 'resident_id-2', 'integer', true);
reset search_path;
revoke all on all tables in schema fixture_r01_v20260904_1_hidden_b from public, anon, authenticated;
grant usage on schema fixture_r01_v20260904_1_hidden_b to dilli_judge_executor;
grant select on all tables in schema fixture_r01_v20260904_1_hidden_b to dilli_judge_executor;
analyze fixture_r01_v20260904_1_hidden_b."catalog_columns";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (1, '2026-09-04.1-hidden_b', 'fixture_r01_v20260904_1_hidden_b', '2026-09-04.1', true, 'ordered', '["attribute","data_type"]'::jsonb, '[["name-2","text"],["resident_id-2","integer"]]'::jsonb, '[25,25]'::jsonb);

insert into game_private.questions (ruin_id, dataset_version, allowed_tables) values
        (2, '2026-09-04.1', '["column_keys"]'::jsonb);

insert into game_private.question_help values
        (2, '2026-09-04.1', 'Keys to the Bus Bay', 'Some attributes can identify a `bus` on their own. Return each `attribute` whose `key_kind` is `primary` or `candidate`. Sort by `attribute`.', '["A unique identifier is a primary or candidate key; match either with a set membership test."]'::jsonb, 'SELECT attribute
FROM column_keys
WHERE entity = ''bus''
  AND key_kind IN (''primary'', ''candidate'')
ORDER BY attribute;');

create schema fixture_r02_v20260904_1_visible;
revoke all on schema fixture_r02_v20260904_1_visible from public, anon, authenticated;
set search_path = fixture_r02_v20260904_1_visible, pg_catalog;
CREATE TABLE "column_keys" ("entity" text, "attribute" text, "key_kind" text, "nullable" boolean);
INSERT INTO "column_keys" VALUES
('bus', 'bus_id', 'primary', false),
('bus', 'registration', 'candidate', false),
('bus', 'radio_code', 'unique', true),
('bus', 'colour', 'none', false),
('driver', 'licence', 'candidate', false),
('bus', 'unknown', NULL, true);
reset search_path;
revoke all on all tables in schema fixture_r02_v20260904_1_visible from public, anon, authenticated;
grant usage on schema fixture_r02_v20260904_1_visible to dilli_judge_executor;
grant select on all tables in schema fixture_r02_v20260904_1_visible to dilli_judge_executor;
analyze fixture_r02_v20260904_1_visible."column_keys";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (2, '2026-09-04.1-visible', 'fixture_r02_v20260904_1_visible', '2026-09-04.1', false, 'ordered', '["attribute"]'::jsonb, '[["bus_id"],["registration"]]'::jsonb, '[25]'::jsonb);

create schema fixture_r02_v20260904_1_hidden_a;
revoke all on schema fixture_r02_v20260904_1_hidden_a from public, anon, authenticated;
set search_path = fixture_r02_v20260904_1_hidden_a, pg_catalog;
CREATE TABLE "column_keys" ("entity" text, "attribute" text, "key_kind" text, "nullable" boolean);
INSERT INTO "column_keys" VALUES
('bus', 'unknown-1', NULL, true),
('driver', 'licence-1', 'candidate', false),
('bus', 'colour-1', 'none', false),
('bus', 'radio_code-1', 'unique', true),
('bus', 'registration-1', 'candidate', false),
('bus', 'bus_id-1', 'primary', false);
reset search_path;
revoke all on all tables in schema fixture_r02_v20260904_1_hidden_a from public, anon, authenticated;
grant usage on schema fixture_r02_v20260904_1_hidden_a to dilli_judge_executor;
grant select on all tables in schema fixture_r02_v20260904_1_hidden_a to dilli_judge_executor;
analyze fixture_r02_v20260904_1_hidden_a."column_keys";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (2, '2026-09-04.1-hidden_a', 'fixture_r02_v20260904_1_hidden_a', '2026-09-04.1', true, 'ordered', '["attribute"]'::jsonb, '[["bus_id-1"],["registration-1"]]'::jsonb, '[25]'::jsonb);

create schema fixture_r02_v20260904_1_hidden_b;
revoke all on schema fixture_r02_v20260904_1_hidden_b from public, anon, authenticated;
set search_path = fixture_r02_v20260904_1_hidden_b, pg_catalog;
CREATE TABLE "column_keys" ("entity" text, "attribute" text, "key_kind" text, "nullable" boolean);
INSERT INTO "column_keys" VALUES
('bus', 'unknown-2', NULL, true),
('bus', 'colour-2', 'none', false),
('bus', 'radio_code-2', 'unique', true),
('bus', 'registration-2', 'candidate', false),
('bus', 'bus_id-2', 'primary', false);
reset search_path;
revoke all on all tables in schema fixture_r02_v20260904_1_hidden_b from public, anon, authenticated;
grant usage on schema fixture_r02_v20260904_1_hidden_b to dilli_judge_executor;
grant select on all tables in schema fixture_r02_v20260904_1_hidden_b to dilli_judge_executor;
analyze fixture_r02_v20260904_1_hidden_b."column_keys";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (2, '2026-09-04.1-hidden_b', 'fixture_r02_v20260904_1_hidden_b', '2026-09-04.1', true, 'ordered', '["attribute"]'::jsonb, '[["bus_id-2"],["registration-2"]]'::jsonb, '[25]'::jsonb);

insert into game_private.questions (ruin_id, dataset_version, allowed_tables) values
        (3, '2026-09-04.1', '["foreign_keys"]'::jsonb);

insert into game_private.question_help values
        (3, '2026-09-04.1', 'Tracing the Family Links', 'The register records foreign keys. List every reference that points at the `family` entity: return `child_entity` and `child_attribute`, ordered by both.', '["A foreign key that references `family` is a row whose parent entity is `family`."]'::jsonb, 'SELECT child_entity, child_attribute
FROM foreign_keys
WHERE parent_entity = ''family''
ORDER BY child_entity, child_attribute;');

create schema fixture_r03_v20260904_1_visible;
revoke all on schema fixture_r03_v20260904_1_visible from public, anon, authenticated;
set search_path = fixture_r03_v20260904_1_visible, pg_catalog;
CREATE TABLE "foreign_keys" ("child_entity" text, "child_attribute" text, "parent_entity" text, "parent_attribute" text);
INSERT INTO "foreign_keys" VALUES
('residents', 'family_id', 'family', 'id'),
('ration_cards', 'household', 'family', 'id'),
('residents', 'shelter_id', 'shelter', 'id'),
('families', 'ward', 'ward', 'id');
reset search_path;
revoke all on all tables in schema fixture_r03_v20260904_1_visible from public, anon, authenticated;
grant usage on schema fixture_r03_v20260904_1_visible to dilli_judge_executor;
grant select on all tables in schema fixture_r03_v20260904_1_visible to dilli_judge_executor;
analyze fixture_r03_v20260904_1_visible."foreign_keys";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (3, '2026-09-04.1-visible', 'fixture_r03_v20260904_1_visible', '2026-09-04.1', false, 'ordered', '["child_entity","child_attribute"]'::jsonb, '[["ration_cards","household"],["residents","family_id"]]'::jsonb, '[25,25]'::jsonb);

create schema fixture_r03_v20260904_1_hidden_a;
revoke all on schema fixture_r03_v20260904_1_hidden_a from public, anon, authenticated;
set search_path = fixture_r03_v20260904_1_hidden_a, pg_catalog;
CREATE TABLE "foreign_keys" ("child_entity" text, "child_attribute" text, "parent_entity" text, "parent_attribute" text);
INSERT INTO "foreign_keys" VALUES
('families-1', 'ward', 'ward', 'id'),
('residents-1', 'shelter_id', 'shelter', 'id'),
('ration_cards-1', 'household', 'family', 'id'),
('residents-1', 'family_id', 'family', 'id');
reset search_path;
revoke all on all tables in schema fixture_r03_v20260904_1_hidden_a from public, anon, authenticated;
grant usage on schema fixture_r03_v20260904_1_hidden_a to dilli_judge_executor;
grant select on all tables in schema fixture_r03_v20260904_1_hidden_a to dilli_judge_executor;
analyze fixture_r03_v20260904_1_hidden_a."foreign_keys";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (3, '2026-09-04.1-hidden_a', 'fixture_r03_v20260904_1_hidden_a', '2026-09-04.1', true, 'ordered', '["child_entity","child_attribute"]'::jsonb, '[["ration_cards-1","household"],["residents-1","family_id"]]'::jsonb, '[25,25]'::jsonb);

create schema fixture_r03_v20260904_1_hidden_b;
revoke all on schema fixture_r03_v20260904_1_hidden_b from public, anon, authenticated;
set search_path = fixture_r03_v20260904_1_hidden_b, pg_catalog;
CREATE TABLE "foreign_keys" ("child_entity" text, "child_attribute" text, "parent_entity" text, "parent_attribute" text);
INSERT INTO "foreign_keys" VALUES
('families-2', 'ward', 'ward', 'id'),
('ration_cards-2', 'household', 'family', 'id'),
('residents-2', 'family_id', 'family', 'id');
reset search_path;
revoke all on all tables in schema fixture_r03_v20260904_1_hidden_b from public, anon, authenticated;
grant usage on schema fixture_r03_v20260904_1_hidden_b to dilli_judge_executor;
grant select on all tables in schema fixture_r03_v20260904_1_hidden_b to dilli_judge_executor;
analyze fixture_r03_v20260904_1_hidden_b."foreign_keys";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (3, '2026-09-04.1-hidden_b', 'fixture_r03_v20260904_1_hidden_b', '2026-09-04.1', true, 'ordered', '["child_entity","child_attribute"]'::jsonb, '[["ration_cards-2","household"],["residents-2","family_id"]]'::jsonb, '[25,25]'::jsonb);

insert into game_private.questions (ruin_id, dataset_version, allowed_tables) values
        (4, '2026-09-04.1', '["change_log"]'::jsonb);

insert into game_private.question_help values
        (4, '2026-09-04.1', 'Evidence of the Rebuild', 'The records room keeps a change log. Return `object_name` and `op` for every entry whose `op_kind` is `DDL`, newest first by `changed_at`.', '["Data-definition changes are the `DDL` rows; filter on `op_kind`, then order by time descending."]'::jsonb, 'SELECT object_name, op
FROM change_log
WHERE op_kind = ''DDL''
ORDER BY changed_at DESC;');

create schema fixture_r04_v20260904_1_visible;
revoke all on schema fixture_r04_v20260904_1_visible from public, anon, authenticated;
set search_path = fixture_r04_v20260904_1_visible, pg_catalog;
CREATE TABLE "change_log" ("op" text, "object_name" text, "op_kind" text, "changed_at" timestamp);
INSERT INTO "change_log" VALUES
('CREATE TABLE', 'shelters', 'DDL', '2042-01-02 10:00:00'),
('INSERT', 'residents', 'DML', '2042-01-04 10:00:00'),
('ALTER TABLE', 'pumps', 'DDL', '2042-01-03 10:00:00'),
('UPDATE', 'pumps', 'DML', NULL);
reset search_path;
revoke all on all tables in schema fixture_r04_v20260904_1_visible from public, anon, authenticated;
grant usage on schema fixture_r04_v20260904_1_visible to dilli_judge_executor;
grant select on all tables in schema fixture_r04_v20260904_1_visible to dilli_judge_executor;
analyze fixture_r04_v20260904_1_visible."change_log";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (4, '2026-09-04.1-visible', 'fixture_r04_v20260904_1_visible', '2026-09-04.1', false, 'ordered', '["object_name","op"]'::jsonb, '[["pumps","ALTER TABLE"],["shelters","CREATE TABLE"]]'::jsonb, '[25,25]'::jsonb);

create schema fixture_r04_v20260904_1_hidden_a;
revoke all on schema fixture_r04_v20260904_1_hidden_a from public, anon, authenticated;
set search_path = fixture_r04_v20260904_1_hidden_a, pg_catalog;
CREATE TABLE "change_log" ("op" text, "object_name" text, "op_kind" text, "changed_at" timestamp);
INSERT INTO "change_log" VALUES
('UPDATE', 'pumps-1', 'DML', NULL),
('ALTER TABLE', 'pumps-1', 'DDL', '2042-01-03 10:00:00'),
('INSERT', 'residents-1', 'DML', '2042-01-04 10:00:00'),
('CREATE TABLE', 'shelters-1', 'DDL', '2042-01-02 10:00:00');
reset search_path;
revoke all on all tables in schema fixture_r04_v20260904_1_hidden_a from public, anon, authenticated;
grant usage on schema fixture_r04_v20260904_1_hidden_a to dilli_judge_executor;
grant select on all tables in schema fixture_r04_v20260904_1_hidden_a to dilli_judge_executor;
analyze fixture_r04_v20260904_1_hidden_a."change_log";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (4, '2026-09-04.1-hidden_a', 'fixture_r04_v20260904_1_hidden_a', '2026-09-04.1', true, 'ordered', '["object_name","op"]'::jsonb, '[["pumps-1","ALTER TABLE"],["shelters-1","CREATE TABLE"]]'::jsonb, '[25,25]'::jsonb);

create schema fixture_r04_v20260904_1_hidden_b;
revoke all on schema fixture_r04_v20260904_1_hidden_b from public, anon, authenticated;
set search_path = fixture_r04_v20260904_1_hidden_b, pg_catalog;
CREATE TABLE "change_log" ("op" text, "object_name" text, "op_kind" text, "changed_at" timestamp);
INSERT INTO "change_log" VALUES
('UPDATE', 'pumps-2', 'DML', NULL),
('INSERT', 'residents-2', 'DML', '2042-01-04 10:00:00'),
('CREATE TABLE', 'shelters-2', 'DDL', '2042-01-02 10:00:00');
reset search_path;
revoke all on all tables in schema fixture_r04_v20260904_1_hidden_b from public, anon, authenticated;
grant usage on schema fixture_r04_v20260904_1_hidden_b to dilli_judge_executor;
grant select on all tables in schema fixture_r04_v20260904_1_hidden_b to dilli_judge_executor;
analyze fixture_r04_v20260904_1_hidden_b."change_log";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (4, '2026-09-04.1-hidden_b', 'fixture_r04_v20260904_1_hidden_b', '2026-09-04.1', true, 'ordered', '["object_name","op"]'::jsonb, '[["shelters-2","CREATE TABLE"]]'::jsonb, '[25,25]'::jsonb);

insert into game_private.questions (ruin_id, dataset_version, allowed_tables) values
        (5, '2026-09-04.1', '["access_grants"]'::jsonb);

insert into game_private.question_help values
        (5, '2026-09-04.1', 'Who Holds the Keys', 'List `grantee` and `object_name` where a `SELECT` privilege was granted (`granted` is true). Sort by `grantee`, then `object_name`.', '["Only rows where the privilege is `SELECT` and the boolean `granted` is true count."]'::jsonb, 'SELECT grantee, object_name
FROM access_grants
WHERE privilege = ''SELECT''
  AND granted
ORDER BY grantee, object_name;');

create schema fixture_r05_v20260904_1_visible;
revoke all on schema fixture_r05_v20260904_1_visible from public, anon, authenticated;
set search_path = fixture_r05_v20260904_1_visible, pg_catalog;
CREATE TABLE "access_grants" ("grantee" text, "object_name" text, "privilege" text, "granted" boolean);
INSERT INTO "access_grants" VALUES
('scout', 'shelters', 'SELECT', true),
('archivist', 'records', 'SELECT', true),
('archivist', 'maps', 'SELECT', true),
('porter', 'crates', 'SELECT', false),
('builder', 'repairs', 'INSERT', true),
('unknown', 'maps', 'SELECT', NULL);
reset search_path;
revoke all on all tables in schema fixture_r05_v20260904_1_visible from public, anon, authenticated;
grant usage on schema fixture_r05_v20260904_1_visible to dilli_judge_executor;
grant select on all tables in schema fixture_r05_v20260904_1_visible to dilli_judge_executor;
analyze fixture_r05_v20260904_1_visible."access_grants";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (5, '2026-09-04.1-visible', 'fixture_r05_v20260904_1_visible', '2026-09-04.1', false, 'ordered', '["grantee","object_name"]'::jsonb, '[["archivist","maps"],["archivist","records"],["scout","shelters"]]'::jsonb, '[25,25]'::jsonb);

create schema fixture_r05_v20260904_1_hidden_a;
revoke all on schema fixture_r05_v20260904_1_hidden_a from public, anon, authenticated;
set search_path = fixture_r05_v20260904_1_hidden_a, pg_catalog;
CREATE TABLE "access_grants" ("grantee" text, "object_name" text, "privilege" text, "granted" boolean);
INSERT INTO "access_grants" VALUES
('unknown-1', 'maps', 'SELECT', NULL),
('builder-1', 'repairs', 'INSERT', true),
('porter-1', 'crates', 'SELECT', false),
('archivist-1', 'maps', 'SELECT', true),
('archivist-1', 'records', 'SELECT', true),
('scout-1', 'shelters', 'SELECT', true);
reset search_path;
revoke all on all tables in schema fixture_r05_v20260904_1_hidden_a from public, anon, authenticated;
grant usage on schema fixture_r05_v20260904_1_hidden_a to dilli_judge_executor;
grant select on all tables in schema fixture_r05_v20260904_1_hidden_a to dilli_judge_executor;
analyze fixture_r05_v20260904_1_hidden_a."access_grants";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (5, '2026-09-04.1-hidden_a', 'fixture_r05_v20260904_1_hidden_a', '2026-09-04.1', true, 'ordered', '["grantee","object_name"]'::jsonb, '[["archivist-1","maps"],["archivist-1","records"],["scout-1","shelters"]]'::jsonb, '[25,25]'::jsonb);

create schema fixture_r05_v20260904_1_hidden_b;
revoke all on schema fixture_r05_v20260904_1_hidden_b from public, anon, authenticated;
set search_path = fixture_r05_v20260904_1_hidden_b, pg_catalog;
CREATE TABLE "access_grants" ("grantee" text, "object_name" text, "privilege" text, "granted" boolean);
INSERT INTO "access_grants" VALUES
('unknown-2', 'maps', 'SELECT', NULL),
('porter-2', 'crates', 'SELECT', false),
('archivist-2', 'maps', 'SELECT', true),
('archivist-2', 'records', 'SELECT', true),
('scout-2', 'shelters', 'SELECT', true);
reset search_path;
revoke all on all tables in schema fixture_r05_v20260904_1_hidden_b from public, anon, authenticated;
grant usage on schema fixture_r05_v20260904_1_hidden_b to dilli_judge_executor;
grant select on all tables in schema fixture_r05_v20260904_1_hidden_b to dilli_judge_executor;
analyze fixture_r05_v20260904_1_hidden_b."access_grants";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (5, '2026-09-04.1-hidden_b', 'fixture_r05_v20260904_1_hidden_b', '2026-09-04.1', true, 'ordered', '["grantee","object_name"]'::jsonb, '[["archivist-2","maps"],["archivist-2","records"],["scout-2","shelters"]]'::jsonb, '[25,25]'::jsonb);

insert into game_private.questions (ruin_id, dataset_version, allowed_tables) values
        (6, '2026-09-04.1', '["stalls"]'::jsonb);

insert into game_private.question_help values
        (6, '2026-09-04.1', 'The Last Open Stalls', 'Return `stall_id` for K-7 stalls whose status is `open`. Sort by `stall_id`.', '["Filter both `ward_code` and `status`, then use `ORDER BY`."]'::jsonb, 'SELECT stall_id
FROM stalls
WHERE ward_code = ''K-7''
  AND status = ''open''
ORDER BY stall_id;');

create schema fixture_r06_v20260904_1_visible;
revoke all on schema fixture_r06_v20260904_1_visible from public, anon, authenticated;
set search_path = fixture_r06_v20260904_1_visible, pg_catalog;
CREATE TABLE "stalls" ("stall_id" integer, "stall_name" text, "ward_code" text, "status" text, "daily_rations" integer);
INSERT INTO "stalls" VALUES
(101, 'Copper Kettle', 'K-7', 'closed', 0),
(102, 'Moonlight Grain', 'K-7', 'open', 28),
(103, 'Red Fort Repairs', 'K-4', 'open', 12),
(104, 'Old Clock Spices', 'K-7', NULL, 7),
(105, 'Yamuna Filters', 'K-9', 'open', 19),
(107, 'Paranthe Power', 'K-7', 'open', 31);
reset search_path;
revoke all on all tables in schema fixture_r06_v20260904_1_visible from public, anon, authenticated;
grant usage on schema fixture_r06_v20260904_1_visible to dilli_judge_executor;
grant select on all tables in schema fixture_r06_v20260904_1_visible to dilli_judge_executor;
analyze fixture_r06_v20260904_1_visible."stalls";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (6, '2026-09-04.1-visible', 'fixture_r06_v20260904_1_visible', '2026-09-04.1', false, 'ordered', '["stall_id"]'::jsonb, '[[102],[107]]'::jsonb, '[23]'::jsonb);

create schema fixture_r06_v20260904_1_hidden_a;
revoke all on schema fixture_r06_v20260904_1_hidden_a from public, anon, authenticated;
set search_path = fixture_r06_v20260904_1_hidden_a, pg_catalog;
CREATE TABLE "stalls" ("stall_id" integer, "stall_name" text, "ward_code" text, "status" text, "daily_rations" integer);
INSERT INTO "stalls" VALUES
(207, 'Paranthe Power', 'K-7', 'open', 31),
(205, 'Yamuna Filters', 'K-9', 'open', 19),
(204, 'Old Clock Spices', 'K-7', NULL, 7),
(203, 'Red Fort Repairs', 'K-4', 'open', 12),
(202, 'Moonlight Grain', 'K-7', 'open', 28),
(201, 'Copper Kettle', 'K-7', 'closed', 0);
reset search_path;
revoke all on all tables in schema fixture_r06_v20260904_1_hidden_a from public, anon, authenticated;
grant usage on schema fixture_r06_v20260904_1_hidden_a to dilli_judge_executor;
grant select on all tables in schema fixture_r06_v20260904_1_hidden_a to dilli_judge_executor;
analyze fixture_r06_v20260904_1_hidden_a."stalls";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (6, '2026-09-04.1-hidden_a', 'fixture_r06_v20260904_1_hidden_a', '2026-09-04.1', true, 'ordered', '["stall_id"]'::jsonb, '[[202],[207]]'::jsonb, '[23]'::jsonb);

create schema fixture_r06_v20260904_1_hidden_b;
revoke all on schema fixture_r06_v20260904_1_hidden_b from public, anon, authenticated;
set search_path = fixture_r06_v20260904_1_hidden_b, pg_catalog;
CREATE TABLE "stalls" ("stall_id" integer, "stall_name" text, "ward_code" text, "status" text, "daily_rations" integer);
INSERT INTO "stalls" VALUES
(307, 'Paranthe Power', 'K-7', 'open', 31),
(304, 'Old Clock Spices', 'K-7', NULL, 7),
(303, 'Red Fort Repairs', 'K-4', 'open', 12),
(302, 'Moonlight Grain', 'K-7', 'open', 28),
(301, 'Copper Kettle', 'K-7', 'closed', 0);
reset search_path;
revoke all on all tables in schema fixture_r06_v20260904_1_hidden_b from public, anon, authenticated;
grant usage on schema fixture_r06_v20260904_1_hidden_b to dilli_judge_executor;
grant select on all tables in schema fixture_r06_v20260904_1_hidden_b to dilli_judge_executor;
analyze fixture_r06_v20260904_1_hidden_b."stalls";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (6, '2026-09-04.1-hidden_b', 'fixture_r06_v20260904_1_hidden_b', '2026-09-04.1', true, 'ordered', '["stall_id"]'::jsonb, '[[302],[307]]'::jsonb, '[23]'::jsonb);

insert into game_private.questions (ruin_id, dataset_version, allowed_tables) values
        (7, '2026-09-04.1', '["pilgrims"]'::jsonb);

insert into game_private.question_help values
        (7, '2026-09-04.1', 'Every Ward Represented', 'Pilgrims gather on the steps. Return each distinct `home_ward` that appears in `pilgrims` — one row per ward — sorted by `home_ward`.', '["Collapse repeated wards to one row each with `DISTINCT`."]'::jsonb, 'SELECT DISTINCT home_ward
FROM pilgrims
ORDER BY home_ward;');

create schema fixture_r07_v20260904_1_visible;
revoke all on schema fixture_r07_v20260904_1_visible from public, anon, authenticated;
set search_path = fixture_r07_v20260904_1_visible, pg_catalog;
CREATE TABLE "pilgrims" ("name" text, "home_ward" text, "arrival_day" integer);
INSERT INTO "pilgrims" VALUES
('Asha', 'W-2', 1),
('Dev', 'W-1', 2),
('Mira', 'W-2', 3),
('Noor', NULL, 4),
('Adi', NULL, 5);
reset search_path;
revoke all on all tables in schema fixture_r07_v20260904_1_visible from public, anon, authenticated;
grant usage on schema fixture_r07_v20260904_1_visible to dilli_judge_executor;
grant select on all tables in schema fixture_r07_v20260904_1_visible to dilli_judge_executor;
analyze fixture_r07_v20260904_1_visible."pilgrims";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (7, '2026-09-04.1-visible', 'fixture_r07_v20260904_1_visible', '2026-09-04.1', false, 'ordered', '["home_ward"]'::jsonb, '[["W-1"],["W-2"],[null]]'::jsonb, '[25]'::jsonb);

create schema fixture_r07_v20260904_1_hidden_a;
revoke all on schema fixture_r07_v20260904_1_hidden_a from public, anon, authenticated;
set search_path = fixture_r07_v20260904_1_hidden_a, pg_catalog;
CREATE TABLE "pilgrims" ("name" text, "home_ward" text, "arrival_day" integer);
INSERT INTO "pilgrims" VALUES
('Adi', NULL, 5),
('Noor', NULL, 4),
('Mira', 'W-2-1', 3),
('Dev', 'W-1-1', 2),
('Asha', 'W-2-1', 1);
reset search_path;
revoke all on all tables in schema fixture_r07_v20260904_1_hidden_a from public, anon, authenticated;
grant usage on schema fixture_r07_v20260904_1_hidden_a to dilli_judge_executor;
grant select on all tables in schema fixture_r07_v20260904_1_hidden_a to dilli_judge_executor;
analyze fixture_r07_v20260904_1_hidden_a."pilgrims";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (7, '2026-09-04.1-hidden_a', 'fixture_r07_v20260904_1_hidden_a', '2026-09-04.1', true, 'ordered', '["home_ward"]'::jsonb, '[["W-1-1"],["W-2-1"],[null]]'::jsonb, '[25]'::jsonb);

create schema fixture_r07_v20260904_1_hidden_b;
revoke all on schema fixture_r07_v20260904_1_hidden_b from public, anon, authenticated;
set search_path = fixture_r07_v20260904_1_hidden_b, pg_catalog;
CREATE TABLE "pilgrims" ("name" text, "home_ward" text, "arrival_day" integer);
INSERT INTO "pilgrims" VALUES
('Adi', NULL, 5),
('Mira', 'W-2-2', 3),
('Dev', 'W-1-2', 2),
('Asha', 'W-2-2', 1);
reset search_path;
revoke all on all tables in schema fixture_r07_v20260904_1_hidden_b from public, anon, authenticated;
grant usage on schema fixture_r07_v20260904_1_hidden_b to dilli_judge_executor;
grant select on all tables in schema fixture_r07_v20260904_1_hidden_b to dilli_judge_executor;
analyze fixture_r07_v20260904_1_hidden_b."pilgrims";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (7, '2026-09-04.1-hidden_b', 'fixture_r07_v20260904_1_hidden_b', '2026-09-04.1', true, 'ordered', '["home_ward"]'::jsonb, '[["W-1-2"],["W-2-2"],[null]]'::jsonb, '[25]'::jsonb);

insert into game_private.questions (ruin_id, dataset_version, allowed_tables) values
        (8, '2026-09-04.1', '["shops"]'::jsonb);

insert into game_private.question_help values
        (8, '2026-09-04.1', 'The Paper Traders', 'Return `shop_name` for every shop whose `trade` mentions paper in any capitalisation. Sort by `shop_name`.', '["Match anywhere in the text, case-insensitively, using wildcards around the word."]'::jsonb, 'SELECT shop_name
FROM shops
WHERE trade ILIKE ''%paper%''
ORDER BY shop_name;');

create schema fixture_r08_v20260904_1_visible;
revoke all on schema fixture_r08_v20260904_1_visible from public, anon, authenticated;
set search_path = fixture_r08_v20260904_1_visible, pg_catalog;
CREATE TABLE "shops" ("shop_name" text, "trade" text);
INSERT INTO "shops" VALUES
('Scroll House', 'handmade PAPER'),
('Paper Lantern', 'lamps'),
('Ink Corner', 'paper and ink'),
('Lost Ledger', NULL),
('Wrapping Works', 'wastepaper');
reset search_path;
revoke all on all tables in schema fixture_r08_v20260904_1_visible from public, anon, authenticated;
grant usage on schema fixture_r08_v20260904_1_visible to dilli_judge_executor;
grant select on all tables in schema fixture_r08_v20260904_1_visible to dilli_judge_executor;
analyze fixture_r08_v20260904_1_visible."shops";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (8, '2026-09-04.1-visible', 'fixture_r08_v20260904_1_visible', '2026-09-04.1', false, 'ordered', '["shop_name"]'::jsonb, '[["Ink Corner"],["Scroll House"],["Wrapping Works"]]'::jsonb, '[25]'::jsonb);

create schema fixture_r08_v20260904_1_hidden_a;
revoke all on schema fixture_r08_v20260904_1_hidden_a from public, anon, authenticated;
set search_path = fixture_r08_v20260904_1_hidden_a, pg_catalog;
CREATE TABLE "shops" ("shop_name" text, "trade" text);
INSERT INTO "shops" VALUES
('Wrapping Works-1', 'wastepaper'),
('Lost Ledger-1', NULL),
('Ink Corner-1', 'paper and ink'),
('Paper Lantern-1', 'lamps'),
('Scroll House-1', 'handmade PAPER');
reset search_path;
revoke all on all tables in schema fixture_r08_v20260904_1_hidden_a from public, anon, authenticated;
grant usage on schema fixture_r08_v20260904_1_hidden_a to dilli_judge_executor;
grant select on all tables in schema fixture_r08_v20260904_1_hidden_a to dilli_judge_executor;
analyze fixture_r08_v20260904_1_hidden_a."shops";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (8, '2026-09-04.1-hidden_a', 'fixture_r08_v20260904_1_hidden_a', '2026-09-04.1', true, 'ordered', '["shop_name"]'::jsonb, '[["Ink Corner-1"],["Scroll House-1"],["Wrapping Works-1"]]'::jsonb, '[25]'::jsonb);

create schema fixture_r08_v20260904_1_hidden_b;
revoke all on schema fixture_r08_v20260904_1_hidden_b from public, anon, authenticated;
set search_path = fixture_r08_v20260904_1_hidden_b, pg_catalog;
CREATE TABLE "shops" ("shop_name" text, "trade" text);
INSERT INTO "shops" VALUES
('Wrapping Works-2', 'wastepaper'),
('Ink Corner-2', 'paper and ink'),
('Paper Lantern-2', 'lamps'),
('Scroll House-2', 'handmade PAPER');
reset search_path;
revoke all on all tables in schema fixture_r08_v20260904_1_hidden_b from public, anon, authenticated;
grant usage on schema fixture_r08_v20260904_1_hidden_b to dilli_judge_executor;
grant select on all tables in schema fixture_r08_v20260904_1_hidden_b to dilli_judge_executor;
analyze fixture_r08_v20260904_1_hidden_b."shops";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (8, '2026-09-04.1-hidden_b', 'fixture_r08_v20260904_1_hidden_b', '2026-09-04.1', true, 'ordered', '["shop_name"]'::jsonb, '[["Ink Corner-2"],["Scroll House-2"],["Wrapping Works-2"]]'::jsonb, '[25]'::jsonb);

insert into game_private.questions (ruin_id, dataset_version, allowed_tables) values
        (9, '2026-09-04.1', '["vaults"]'::jsonb);

insert into game_private.question_help values
        (9, '2026-09-04.1', 'Unsealed in the Silver Lane', 'Return `vault_id` for vaults in ward `D-1`, `D-3`, or `D-9` that are not sealed (`sealed` is false). Sort by `vault_id`.', '["Combine a set-membership check on the ward with a negation of `sealed`."]'::jsonb, 'SELECT vault_id
FROM vaults
WHERE ward_code IN (''D-1'', ''D-3'', ''D-9'')
  AND NOT sealed
ORDER BY vault_id;');

create schema fixture_r09_v20260904_1_visible;
revoke all on schema fixture_r09_v20260904_1_visible from public, anon, authenticated;
set search_path = fixture_r09_v20260904_1_visible, pg_catalog;
CREATE TABLE "vaults" ("vault_id" integer, "ward_code" text, "sealed" boolean);
INSERT INTO "vaults" VALUES
(11, 'D-1', false),
(12, 'D-3', false),
(13, 'D-9', false),
(14, 'D-2', false),
(15, 'D-1', true),
(16, 'D-3', NULL),
(17, NULL, false);
reset search_path;
revoke all on all tables in schema fixture_r09_v20260904_1_visible from public, anon, authenticated;
grant usage on schema fixture_r09_v20260904_1_visible to dilli_judge_executor;
grant select on all tables in schema fixture_r09_v20260904_1_visible to dilli_judge_executor;
analyze fixture_r09_v20260904_1_visible."vaults";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (9, '2026-09-04.1-visible', 'fixture_r09_v20260904_1_visible', '2026-09-04.1', false, 'ordered', '["vault_id"]'::jsonb, '[[11],[12],[13]]'::jsonb, '[23]'::jsonb);

create schema fixture_r09_v20260904_1_hidden_a;
revoke all on schema fixture_r09_v20260904_1_hidden_a from public, anon, authenticated;
set search_path = fixture_r09_v20260904_1_hidden_a, pg_catalog;
CREATE TABLE "vaults" ("vault_id" integer, "ward_code" text, "sealed" boolean);
INSERT INTO "vaults" VALUES
(117, NULL, false),
(116, 'D-3', NULL),
(115, 'D-1', true),
(114, 'D-2', false),
(113, 'D-9', false),
(112, 'D-3', false),
(111, 'D-1', false);
reset search_path;
revoke all on all tables in schema fixture_r09_v20260904_1_hidden_a from public, anon, authenticated;
grant usage on schema fixture_r09_v20260904_1_hidden_a to dilli_judge_executor;
grant select on all tables in schema fixture_r09_v20260904_1_hidden_a to dilli_judge_executor;
analyze fixture_r09_v20260904_1_hidden_a."vaults";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (9, '2026-09-04.1-hidden_a', 'fixture_r09_v20260904_1_hidden_a', '2026-09-04.1', true, 'ordered', '["vault_id"]'::jsonb, '[[111],[112],[113]]'::jsonb, '[23]'::jsonb);

create schema fixture_r09_v20260904_1_hidden_b;
revoke all on schema fixture_r09_v20260904_1_hidden_b from public, anon, authenticated;
set search_path = fixture_r09_v20260904_1_hidden_b, pg_catalog;
CREATE TABLE "vaults" ("vault_id" integer, "ward_code" text, "sealed" boolean);
INSERT INTO "vaults" VALUES
(217, NULL, false),
(215, 'D-1', true),
(214, 'D-2', false),
(213, 'D-9', false),
(212, 'D-3', false),
(211, 'D-1', false);
reset search_path;
revoke all on all tables in schema fixture_r09_v20260904_1_hidden_b from public, anon, authenticated;
grant usage on schema fixture_r09_v20260904_1_hidden_b to dilli_judge_executor;
grant select on all tables in schema fixture_r09_v20260904_1_hidden_b to dilli_judge_executor;
analyze fixture_r09_v20260904_1_hidden_b."vaults";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (9, '2026-09-04.1-hidden_b', 'fixture_r09_v20260904_1_hidden_b', '2026-09-04.1', true, 'ordered', '["vault_id"]'::jsonb, '[[211],[212],[213]]'::jsonb, '[23]'::jsonb);

insert into game_private.questions (ruin_id, dataset_version, allowed_tables) values
        (10, '2026-09-04.1', '["finds"]'::jsonb);

insert into game_private.question_help values
        (10, '2026-09-04.1', 'The Three Richest Finds', 'Return `item` and `value_coins` for the three most valuable finds, highest value first. Break ties by `item` ascending.', '["Order by value descending, add `item` as a tie-break, then keep only the top rows."]'::jsonb, 'SELECT item, value_coins
FROM finds
ORDER BY value_coins DESC, item
LIMIT 3;');

create schema fixture_r10_v20260904_1_visible;
revoke all on schema fixture_r10_v20260904_1_visible from public, anon, authenticated;
set search_path = fixture_r10_v20260904_1_visible, pg_catalog;
CREATE TABLE "finds" ("item" text, "value_coins" integer);
INSERT INTO "finds" VALUES
('Zinc compass', 90),
('Amber lens', 90),
('Tin whistle', 90),
('Copper dial', 90),
('Worn buckle', 10);
reset search_path;
revoke all on all tables in schema fixture_r10_v20260904_1_visible from public, anon, authenticated;
grant usage on schema fixture_r10_v20260904_1_visible to dilli_judge_executor;
grant select on all tables in schema fixture_r10_v20260904_1_visible to dilli_judge_executor;
analyze fixture_r10_v20260904_1_visible."finds";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (10, '2026-09-04.1-visible', 'fixture_r10_v20260904_1_visible', '2026-09-04.1', false, 'ordered', '["item","value_coins"]'::jsonb, '[["Amber lens",90],["Copper dial",90],["Tin whistle",90]]'::jsonb, '[25,23]'::jsonb);

create schema fixture_r10_v20260904_1_hidden_a;
revoke all on schema fixture_r10_v20260904_1_hidden_a from public, anon, authenticated;
set search_path = fixture_r10_v20260904_1_hidden_a, pg_catalog;
CREATE TABLE "finds" ("item" text, "value_coins" integer);
INSERT INTO "finds" VALUES
('Worn buckle-1', 110),
('Copper dial-1', 190),
('Tin whistle-1', 190),
('Amber lens-1', 190),
('Zinc compass-1', 190);
reset search_path;
revoke all on all tables in schema fixture_r10_v20260904_1_hidden_a from public, anon, authenticated;
grant usage on schema fixture_r10_v20260904_1_hidden_a to dilli_judge_executor;
grant select on all tables in schema fixture_r10_v20260904_1_hidden_a to dilli_judge_executor;
analyze fixture_r10_v20260904_1_hidden_a."finds";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (10, '2026-09-04.1-hidden_a', 'fixture_r10_v20260904_1_hidden_a', '2026-09-04.1', true, 'ordered', '["item","value_coins"]'::jsonb, '[["Amber lens-1",190],["Copper dial-1",190],["Tin whistle-1",190]]'::jsonb, '[25,23]'::jsonb);

create schema fixture_r10_v20260904_1_hidden_b;
revoke all on schema fixture_r10_v20260904_1_hidden_b from public, anon, authenticated;
set search_path = fixture_r10_v20260904_1_hidden_b, pg_catalog;
CREATE TABLE "finds" ("item" text, "value_coins" integer);
INSERT INTO "finds" VALUES
('Worn buckle-2', 210),
('Tin whistle-2', 290),
('Amber lens-2', 290),
('Zinc compass-2', 290);
reset search_path;
revoke all on all tables in schema fixture_r10_v20260904_1_hidden_b from public, anon, authenticated;
grant usage on schema fixture_r10_v20260904_1_hidden_b to dilli_judge_executor;
grant select on all tables in schema fixture_r10_v20260904_1_hidden_b to dilli_judge_executor;
analyze fixture_r10_v20260904_1_hidden_b."finds";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (10, '2026-09-04.1-hidden_b', 'fixture_r10_v20260904_1_hidden_b', '2026-09-04.1', true, 'ordered', '["item","value_coins"]'::jsonb, '[["Amber lens-2",290],["Tin whistle-2",290],["Zinc compass-2",290]]'::jsonb, '[25,23]'::jsonb);

insert into game_private.questions (ruin_id, dataset_version, allowed_tables) values
        (11, '2026-09-04.1', '["recipes"]'::jsonb);

insert into game_private.question_help values
        (11, '2026-09-04.1', 'Karim''s Recipe Cards', 'For each dish return its name upper-cased as `dish_caps` and the length of `notes` as `note_len`. Sort by `dish`.', '["String functions transform each value: one upper-cases text, another counts characters.","Alias the two computed columns exactly as `dish_caps` and `note_len`."]'::jsonb, 'SELECT upper(dish) AS dish_caps, length(notes) AS note_len
FROM recipes
ORDER BY dish;');

create schema fixture_r11_v20260904_1_visible;
revoke all on schema fixture_r11_v20260904_1_visible from public, anon, authenticated;
set search_path = fixture_r11_v20260904_1_visible, pg_catalog;
CREATE TABLE "recipes" ("dish" text, "notes" text);
INSERT INTO "recipes" VALUES
('dal', 'Stir gently'),
('chai', NULL),
('roti', ''),
('rice', 'नींबू');
reset search_path;
revoke all on all tables in schema fixture_r11_v20260904_1_visible from public, anon, authenticated;
grant usage on schema fixture_r11_v20260904_1_visible to dilli_judge_executor;
grant select on all tables in schema fixture_r11_v20260904_1_visible to dilli_judge_executor;
analyze fixture_r11_v20260904_1_visible."recipes";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (11, '2026-09-04.1-visible', 'fixture_r11_v20260904_1_visible', '2026-09-04.1', false, 'ordered', '["dish_caps","note_len"]'::jsonb, '[["CHAI",null],["DAL",11],["RICE",5],["ROTI",0]]'::jsonb, '[25,23]'::jsonb);

create schema fixture_r11_v20260904_1_hidden_a;
revoke all on schema fixture_r11_v20260904_1_hidden_a from public, anon, authenticated;
set search_path = fixture_r11_v20260904_1_hidden_a, pg_catalog;
CREATE TABLE "recipes" ("dish" text, "notes" text);
INSERT INTO "recipes" VALUES
('rice-1', 'नींबू'),
('roti-1', ''),
('chai-1', NULL),
('dal-1', 'Stir gently');
reset search_path;
revoke all on all tables in schema fixture_r11_v20260904_1_hidden_a from public, anon, authenticated;
grant usage on schema fixture_r11_v20260904_1_hidden_a to dilli_judge_executor;
grant select on all tables in schema fixture_r11_v20260904_1_hidden_a to dilli_judge_executor;
analyze fixture_r11_v20260904_1_hidden_a."recipes";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (11, '2026-09-04.1-hidden_a', 'fixture_r11_v20260904_1_hidden_a', '2026-09-04.1', true, 'ordered', '["dish_caps","note_len"]'::jsonb, '[["CHAI-1",null],["DAL-1",11],["RICE-1",5],["ROTI-1",0]]'::jsonb, '[25,23]'::jsonb);

create schema fixture_r11_v20260904_1_hidden_b;
revoke all on schema fixture_r11_v20260904_1_hidden_b from public, anon, authenticated;
set search_path = fixture_r11_v20260904_1_hidden_b, pg_catalog;
CREATE TABLE "recipes" ("dish" text, "notes" text);
INSERT INTO "recipes" VALUES
('rice-2', 'नींबू'),
('chai-2', NULL),
('dal-2', 'Stir gently');
reset search_path;
revoke all on all tables in schema fixture_r11_v20260904_1_hidden_b from public, anon, authenticated;
grant usage on schema fixture_r11_v20260904_1_hidden_b to dilli_judge_executor;
grant select on all tables in schema fixture_r11_v20260904_1_hidden_b to dilli_judge_executor;
analyze fixture_r11_v20260904_1_hidden_b."recipes";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (11, '2026-09-04.1-hidden_b', 'fixture_r11_v20260904_1_hidden_b', '2026-09-04.1', true, 'ordered', '["dish_caps","note_len"]'::jsonb, '[["CHAI-2",null],["DAL-2",11],["RICE-2",5]]'::jsonb, '[25,23]'::jsonb);

insert into game_private.questions (ruin_id, dataset_version, allowed_tables) values
        (12, '2026-09-04.1', '["pumps"]'::jsonb);

insert into game_private.question_help values
        (12, '2026-09-04.1', 'Total Flow at Wazirabad', 'Return `pump_id` and the rounded combined flow `litres_per_min + backup_lpm` as `total_flow`, treating a missing `backup_lpm` as zero. Sort by `pump_id`.', '["A null backup would poison the sum; replace it with zero first.","Round the total to a whole number with a numeric function."]'::jsonb, 'SELECT pump_id, round(litres_per_min + coalesce(backup_lpm, 0)) AS total_flow
FROM pumps
ORDER BY pump_id;');

create schema fixture_r12_v20260904_1_visible;
revoke all on schema fixture_r12_v20260904_1_visible from public, anon, authenticated;
set search_path = fixture_r12_v20260904_1_visible, pg_catalog;
CREATE TABLE "pumps" ("pump_id" integer, "litres_per_min" numeric, "backup_lpm" numeric);
INSERT INTO "pumps" VALUES
(1, 12.4, NULL),
(2, 10.25, 0.25),
(3, 0, 0),
(4, NULL, 7.5),
(5, 8.6, -1.2);
reset search_path;
revoke all on all tables in schema fixture_r12_v20260904_1_visible from public, anon, authenticated;
grant usage on schema fixture_r12_v20260904_1_visible to dilli_judge_executor;
grant select on all tables in schema fixture_r12_v20260904_1_visible to dilli_judge_executor;
analyze fixture_r12_v20260904_1_visible."pumps";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (12, '2026-09-04.1-visible', 'fixture_r12_v20260904_1_visible', '2026-09-04.1', false, 'ordered', '["pump_id","total_flow"]'::jsonb, '[[1,"12"],[2,"11"],[3,"0"],[4,null],[5,"7"]]'::jsonb, '[23,1700]'::jsonb);

create schema fixture_r12_v20260904_1_hidden_a;
revoke all on schema fixture_r12_v20260904_1_hidden_a from public, anon, authenticated;
set search_path = fixture_r12_v20260904_1_hidden_a, pg_catalog;
CREATE TABLE "pumps" ("pump_id" integer, "litres_per_min" numeric, "backup_lpm" numeric);
INSERT INTO "pumps" VALUES
(105, 8.6, -1.2),
(104, NULL, 7.5),
(103, 0, 0),
(102, 10.25, 0.25),
(101, 12.4, NULL);
reset search_path;
revoke all on all tables in schema fixture_r12_v20260904_1_hidden_a from public, anon, authenticated;
grant usage on schema fixture_r12_v20260904_1_hidden_a to dilli_judge_executor;
grant select on all tables in schema fixture_r12_v20260904_1_hidden_a to dilli_judge_executor;
analyze fixture_r12_v20260904_1_hidden_a."pumps";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (12, '2026-09-04.1-hidden_a', 'fixture_r12_v20260904_1_hidden_a', '2026-09-04.1', true, 'ordered', '["pump_id","total_flow"]'::jsonb, '[[101,"12"],[102,"11"],[103,"0"],[104,null],[105,"7"]]'::jsonb, '[23,1700]'::jsonb);

create schema fixture_r12_v20260904_1_hidden_b;
revoke all on schema fixture_r12_v20260904_1_hidden_b from public, anon, authenticated;
set search_path = fixture_r12_v20260904_1_hidden_b, pg_catalog;
CREATE TABLE "pumps" ("pump_id" integer, "litres_per_min" numeric, "backup_lpm" numeric);
INSERT INTO "pumps" VALUES
(205, 8.6, -1.2),
(203, 0, 0),
(202, 10.25, 0.25),
(201, 12.4, NULL);
reset search_path;
revoke all on all tables in schema fixture_r12_v20260904_1_hidden_b from public, anon, authenticated;
grant usage on schema fixture_r12_v20260904_1_hidden_b to dilli_judge_executor;
grant select on all tables in schema fixture_r12_v20260904_1_hidden_b to dilli_judge_executor;
analyze fixture_r12_v20260904_1_hidden_b."pumps";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (12, '2026-09-04.1-hidden_b', 'fixture_r12_v20260904_1_hidden_b', '2026-09-04.1', true, 'ordered', '["pump_id","total_flow"]'::jsonb, '[[201,"12"],[202,"11"],[203,"0"],[205,"7"]]'::jsonb, '[23,1700]'::jsonb);

insert into game_private.questions (ruin_id, dataset_version, allowed_tables) values
        (13, '2026-09-04.1', '["departures"]'::jsonb);

insert into game_private.question_help values
        (13, '2026-09-04.1', 'Departures by Day', 'From `departures`, return each calendar `date` of `depart_at` and the count of trains that day as `trains`. Sort by `date`.', '["Reduce each timestamp to its date before grouping.","Group by that date and count the rows in each group."]'::jsonb, 'SELECT depart_at::date AS date, count(*) AS trains
FROM departures
GROUP BY depart_at::date
ORDER BY date;');

create schema fixture_r13_v20260904_1_visible;
revoke all on schema fixture_r13_v20260904_1_visible from public, anon, authenticated;
set search_path = fixture_r13_v20260904_1_visible, pg_catalog;
CREATE TABLE "departures" ("train" text, "depart_at" timestamp);
INSERT INTO "departures" VALUES
('A', '2042-02-01 23:59:00'),
(NULL, '2042-02-01 01:00:00'),
('B', '2042-02-02 00:00:00'),
('C', NULL);
reset search_path;
revoke all on all tables in schema fixture_r13_v20260904_1_visible from public, anon, authenticated;
grant usage on schema fixture_r13_v20260904_1_visible to dilli_judge_executor;
grant select on all tables in schema fixture_r13_v20260904_1_visible to dilli_judge_executor;
analyze fixture_r13_v20260904_1_visible."departures";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (13, '2026-09-04.1-visible', 'fixture_r13_v20260904_1_visible', '2026-09-04.1', false, 'ordered', '["date","trains"]'::jsonb, '[["2042-02-01T00:00:00.000Z",2],["2042-02-02T00:00:00.000Z",1],[null,1]]'::jsonb, '[1082,20]'::jsonb);

create schema fixture_r13_v20260904_1_hidden_a;
revoke all on schema fixture_r13_v20260904_1_hidden_a from public, anon, authenticated;
set search_path = fixture_r13_v20260904_1_hidden_a, pg_catalog;
CREATE TABLE "departures" ("train" text, "depart_at" timestamp);
INSERT INTO "departures" VALUES
('C', NULL),
('B', '2042-02-03 00:00:00'),
(NULL, '2042-02-02 01:00:00'),
('A', '2042-02-02 23:59:00');
reset search_path;
revoke all on all tables in schema fixture_r13_v20260904_1_hidden_a from public, anon, authenticated;
grant usage on schema fixture_r13_v20260904_1_hidden_a to dilli_judge_executor;
grant select on all tables in schema fixture_r13_v20260904_1_hidden_a to dilli_judge_executor;
analyze fixture_r13_v20260904_1_hidden_a."departures";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (13, '2026-09-04.1-hidden_a', 'fixture_r13_v20260904_1_hidden_a', '2026-09-04.1', true, 'ordered', '["date","trains"]'::jsonb, '[["2042-02-02T00:00:00.000Z",2],["2042-02-03T00:00:00.000Z",1],[null,1]]'::jsonb, '[1082,20]'::jsonb);

create schema fixture_r13_v20260904_1_hidden_b;
revoke all on schema fixture_r13_v20260904_1_hidden_b from public, anon, authenticated;
set search_path = fixture_r13_v20260904_1_hidden_b, pg_catalog;
CREATE TABLE "departures" ("train" text, "depart_at" timestamp);
INSERT INTO "departures" VALUES
('C', NULL),
(NULL, '2042-02-03 01:00:00'),
('A', '2042-02-03 23:59:00');
reset search_path;
revoke all on all tables in schema fixture_r13_v20260904_1_hidden_b from public, anon, authenticated;
grant usage on schema fixture_r13_v20260904_1_hidden_b to dilli_judge_executor;
grant select on all tables in schema fixture_r13_v20260904_1_hidden_b to dilli_judge_executor;
analyze fixture_r13_v20260904_1_hidden_b."departures";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (13, '2026-09-04.1-hidden_b', 'fixture_r13_v20260904_1_hidden_b', '2026-09-04.1', true, 'ordered', '["date","trains"]'::jsonb, '[["2042-02-03T00:00:00.000Z",2],[null,1]]'::jsonb, '[1082,20]'::jsonb);

insert into game_private.questions (ruin_id, dataset_version, allowed_tables) values
        (14, '2026-09-04.1', '["lots"]'::jsonb);

insert into game_private.question_help values
        (14, '2026-09-04.1', 'Crates at Azadpur Mandi', 'Return each `crop` and its total `crates` as `total_crates` across all lots. Sort by `crop`.', '["One output row per crop means grouping by crop.","Sum the crates within each group."]'::jsonb, 'SELECT crop, sum(crates) AS total_crates
FROM lots
GROUP BY crop
ORDER BY crop;');

create schema fixture_r14_v20260904_1_visible;
revoke all on schema fixture_r14_v20260904_1_visible from public, anon, authenticated;
set search_path = fixture_r14_v20260904_1_visible, pg_catalog;
CREATE TABLE "lots" ("crop" text, "crates" integer);
INSERT INTO "lots" VALUES
('rice', 7),
('rice', 7),
('rice', NULL),
('millet', 3),
('millet', -1),
('beans', NULL);
reset search_path;
revoke all on all tables in schema fixture_r14_v20260904_1_visible from public, anon, authenticated;
grant usage on schema fixture_r14_v20260904_1_visible to dilli_judge_executor;
grant select on all tables in schema fixture_r14_v20260904_1_visible to dilli_judge_executor;
analyze fixture_r14_v20260904_1_visible."lots";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (14, '2026-09-04.1-visible', 'fixture_r14_v20260904_1_visible', '2026-09-04.1', false, 'ordered', '["crop","total_crates"]'::jsonb, '[["beans",null],["millet",2],["rice",14]]'::jsonb, '[25,20]'::jsonb);

create schema fixture_r14_v20260904_1_hidden_a;
revoke all on schema fixture_r14_v20260904_1_hidden_a from public, anon, authenticated;
set search_path = fixture_r14_v20260904_1_hidden_a, pg_catalog;
CREATE TABLE "lots" ("crop" text, "crates" integer);
INSERT INTO "lots" VALUES
('beans-1', NULL),
('millet-1', -1),
('millet-1', 3),
('rice-1', NULL),
('rice-1', 7),
('rice-1', 7);
reset search_path;
revoke all on all tables in schema fixture_r14_v20260904_1_hidden_a from public, anon, authenticated;
grant usage on schema fixture_r14_v20260904_1_hidden_a to dilli_judge_executor;
grant select on all tables in schema fixture_r14_v20260904_1_hidden_a to dilli_judge_executor;
analyze fixture_r14_v20260904_1_hidden_a."lots";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (14, '2026-09-04.1-hidden_a', 'fixture_r14_v20260904_1_hidden_a', '2026-09-04.1', true, 'ordered', '["crop","total_crates"]'::jsonb, '[["beans-1",null],["millet-1",2],["rice-1",14]]'::jsonb, '[25,20]'::jsonb);

create schema fixture_r14_v20260904_1_hidden_b;
revoke all on schema fixture_r14_v20260904_1_hidden_b from public, anon, authenticated;
set search_path = fixture_r14_v20260904_1_hidden_b, pg_catalog;
CREATE TABLE "lots" ("crop" text, "crates" integer);
INSERT INTO "lots" VALUES
('beans-2', NULL),
('millet-2', 3),
('rice-2', NULL),
('rice-2', 7),
('rice-2', 7);
reset search_path;
revoke all on all tables in schema fixture_r14_v20260904_1_hidden_b from public, anon, authenticated;
grant usage on schema fixture_r14_v20260904_1_hidden_b to dilli_judge_executor;
grant select on all tables in schema fixture_r14_v20260904_1_hidden_b to dilli_judge_executor;
analyze fixture_r14_v20260904_1_hidden_b."lots";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (14, '2026-09-04.1-hidden_b', 'fixture_r14_v20260904_1_hidden_b', '2026-09-04.1', true, 'ordered', '["crop","total_crates"]'::jsonb, '[["beans-2",null],["millet-2",3],["rice-2",14]]'::jsonb, '[25,20]'::jsonb);

insert into game_private.questions (ruin_id, dataset_version, allowed_tables) values
        (15, '2026-09-04.1', '["heaps"]'::jsonb);

insert into game_private.question_help values
        (15, '2026-09-04.1', 'Heaps Above the Line', 'Return `heap_no` for disposal heaps whose total recovered `metal_kg` exceeds 800. Sort by `heap_no`. `HAVING` is the intended lesson.', '["Filter the groups after they are formed, not the individual rows.","The threshold applies to the summed metal per heap."]'::jsonb, 'SELECT heap_no
FROM heaps
GROUP BY heap_no
HAVING sum(metal_kg) > 800
ORDER BY heap_no;');

create schema fixture_r15_v20260904_1_visible;
revoke all on schema fixture_r15_v20260904_1_visible from public, anon, authenticated;
set search_path = fixture_r15_v20260904_1_visible, pg_catalog;
CREATE TABLE "heaps" ("heap_no" text, "metal_kg" numeric);
INSERT INTO "heaps" VALUES
('H-A', 500),
('H-A', 400),
('H-B', 800),
('H-C', 801),
('H-D', NULL),
('H-E', 1000),
('H-E', -300);
reset search_path;
revoke all on all tables in schema fixture_r15_v20260904_1_visible from public, anon, authenticated;
grant usage on schema fixture_r15_v20260904_1_visible to dilli_judge_executor;
grant select on all tables in schema fixture_r15_v20260904_1_visible to dilli_judge_executor;
analyze fixture_r15_v20260904_1_visible."heaps";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (15, '2026-09-04.1-visible', 'fixture_r15_v20260904_1_visible', '2026-09-04.1', false, 'ordered', '["heap_no"]'::jsonb, '[["H-A"],["H-C"]]'::jsonb, '[25]'::jsonb);

create schema fixture_r15_v20260904_1_hidden_a;
revoke all on schema fixture_r15_v20260904_1_hidden_a from public, anon, authenticated;
set search_path = fixture_r15_v20260904_1_hidden_a, pg_catalog;
CREATE TABLE "heaps" ("heap_no" text, "metal_kg" numeric);
INSERT INTO "heaps" VALUES
('H-E-1', -300),
('H-E-1', 1000),
('H-D-1', NULL),
('H-C-1', 801),
('H-B-1', 800),
('H-A-1', 400),
('H-A-1', 500);
reset search_path;
revoke all on all tables in schema fixture_r15_v20260904_1_hidden_a from public, anon, authenticated;
grant usage on schema fixture_r15_v20260904_1_hidden_a to dilli_judge_executor;
grant select on all tables in schema fixture_r15_v20260904_1_hidden_a to dilli_judge_executor;
analyze fixture_r15_v20260904_1_hidden_a."heaps";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (15, '2026-09-04.1-hidden_a', 'fixture_r15_v20260904_1_hidden_a', '2026-09-04.1', true, 'ordered', '["heap_no"]'::jsonb, '[["H-A-1"],["H-C-1"]]'::jsonb, '[25]'::jsonb);

create schema fixture_r15_v20260904_1_hidden_b;
revoke all on schema fixture_r15_v20260904_1_hidden_b from public, anon, authenticated;
set search_path = fixture_r15_v20260904_1_hidden_b, pg_catalog;
CREATE TABLE "heaps" ("heap_no" text, "metal_kg" numeric);
INSERT INTO "heaps" VALUES
('H-E-2', -300),
('H-D-2', NULL),
('H-C-2', 801),
('H-B-2', 800),
('H-A-2', 400),
('H-A-2', 500);
reset search_path;
revoke all on all tables in schema fixture_r15_v20260904_1_hidden_b from public, anon, authenticated;
grant usage on schema fixture_r15_v20260904_1_hidden_b to dilli_judge_executor;
grant select on all tables in schema fixture_r15_v20260904_1_hidden_b to dilli_judge_executor;
analyze fixture_r15_v20260904_1_hidden_b."heaps";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (15, '2026-09-04.1-hidden_b', 'fixture_r15_v20260904_1_hidden_b', '2026-09-04.1', true, 'ordered', '["heap_no"]'::jsonb, '[["H-A-2"],["H-C-2"]]'::jsonb, '[25]'::jsonb);

insert into game_private.questions (ruin_id, dataset_version, allowed_tables) values
        (16, '2026-09-04.1', '["parcels"]'::jsonb);

insert into game_private.question_help values
        (16, '2026-09-04.1', 'Heavy Parcels per Bin', 'For each `bin`, return the count of parcels weighing at least 20 kg as `heavy_count`. Sort by `bin`. Try `CASE`; equivalent queries work too.', '["Turn each parcel into 1 when heavy and 0 otherwise with `CASE`.","Summing those flags per bin gives the heavy count."]'::jsonb, 'SELECT bin, sum(CASE WHEN weight_kg >= 20 THEN 1 ELSE 0 END) AS heavy_count
FROM parcels
GROUP BY bin
ORDER BY bin;');

create schema fixture_r16_v20260904_1_visible;
revoke all on schema fixture_r16_v20260904_1_visible from public, anon, authenticated;
set search_path = fixture_r16_v20260904_1_visible, pg_catalog;
CREATE TABLE "parcels" ("bin" text, "weight_kg" numeric);
INSERT INTO "parcels" VALUES
('B-A', 20),
('B-A', 21),
('B-A', 19.9),
('B-B', 3),
('B-B', NULL),
('B-C', 40);
reset search_path;
revoke all on all tables in schema fixture_r16_v20260904_1_visible from public, anon, authenticated;
grant usage on schema fixture_r16_v20260904_1_visible to dilli_judge_executor;
grant select on all tables in schema fixture_r16_v20260904_1_visible to dilli_judge_executor;
analyze fixture_r16_v20260904_1_visible."parcels";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (16, '2026-09-04.1-visible', 'fixture_r16_v20260904_1_visible', '2026-09-04.1', false, 'ordered', '["bin","heavy_count"]'::jsonb, '[["B-A",2],["B-B",0],["B-C",1]]'::jsonb, '[25,20]'::jsonb);

create schema fixture_r16_v20260904_1_hidden_a;
revoke all on schema fixture_r16_v20260904_1_hidden_a from public, anon, authenticated;
set search_path = fixture_r16_v20260904_1_hidden_a, pg_catalog;
CREATE TABLE "parcels" ("bin" text, "weight_kg" numeric);
INSERT INTO "parcels" VALUES
('B-C-1', 40),
('B-B-1', NULL),
('B-B-1', 3),
('B-A-1', 19.9),
('B-A-1', 21),
('B-A-1', 20);
reset search_path;
revoke all on all tables in schema fixture_r16_v20260904_1_hidden_a from public, anon, authenticated;
grant usage on schema fixture_r16_v20260904_1_hidden_a to dilli_judge_executor;
grant select on all tables in schema fixture_r16_v20260904_1_hidden_a to dilli_judge_executor;
analyze fixture_r16_v20260904_1_hidden_a."parcels";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (16, '2026-09-04.1-hidden_a', 'fixture_r16_v20260904_1_hidden_a', '2026-09-04.1', true, 'ordered', '["bin","heavy_count"]'::jsonb, '[["B-A-1",2],["B-B-1",0],["B-C-1",1]]'::jsonb, '[25,20]'::jsonb);

create schema fixture_r16_v20260904_1_hidden_b;
revoke all on schema fixture_r16_v20260904_1_hidden_b from public, anon, authenticated;
set search_path = fixture_r16_v20260904_1_hidden_b, pg_catalog;
CREATE TABLE "parcels" ("bin" text, "weight_kg" numeric);
INSERT INTO "parcels" VALUES
('B-C-2', 40),
('B-B-2', 3),
('B-A-2', 19.9),
('B-A-2', 21),
('B-A-2', 20);
reset search_path;
revoke all on all tables in schema fixture_r16_v20260904_1_hidden_b from public, anon, authenticated;
grant usage on schema fixture_r16_v20260904_1_hidden_b to dilli_judge_executor;
grant select on all tables in schema fixture_r16_v20260904_1_hidden_b to dilli_judge_executor;
analyze fixture_r16_v20260904_1_hidden_b."parcels";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (16, '2026-09-04.1-hidden_b', 'fixture_r16_v20260904_1_hidden_b', '2026-09-04.1', true, 'ordered', '["bin","heavy_count"]'::jsonb, '[["B-A-2",2],["B-B-2",0],["B-C-2",1]]'::jsonb, '[25,20]'::jsonb);

insert into game_private.questions (ruin_id, dataset_version, allowed_tables) values
        (17, '2026-09-04.1', '["riders"]'::jsonb);

insert into game_private.question_help values
        (17, '2026-09-04.1', 'Ranking the Rush', 'Return `line`, `rider`, `taps` and `line_rank`: rank descending taps within each line, sharing ranks for ties and leaving gaps. Sort by `line`, `line_rank`, then `rider`.', '["A window function ranks rows without collapsing them.","Partition by `line` and order by `taps` descending so ties share a rank."]'::jsonb, 'SELECT line, rider, taps,
       RANK() OVER (PARTITION BY line ORDER BY taps DESC) AS line_rank
FROM riders
ORDER BY line, line_rank, rider;');

create schema fixture_r17_v20260904_1_visible;
revoke all on schema fixture_r17_v20260904_1_visible from public, anon, authenticated;
set search_path = fixture_r17_v20260904_1_visible, pg_catalog;
CREATE TABLE "riders" ("line" text, "rider" text, "taps" integer);
INSERT INTO "riders" VALUES
('Blue', 'Mira', 40),
('Blue', 'Adi', 40),
('Blue', 'Dev', 20),
('Gold', 'Noor', 25),
('Gold', 'Tara', 10);
reset search_path;
revoke all on all tables in schema fixture_r17_v20260904_1_visible from public, anon, authenticated;
grant usage on schema fixture_r17_v20260904_1_visible to dilli_judge_executor;
grant select on all tables in schema fixture_r17_v20260904_1_visible to dilli_judge_executor;
analyze fixture_r17_v20260904_1_visible."riders";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (17, '2026-09-04.1-visible', 'fixture_r17_v20260904_1_visible', '2026-09-04.1', false, 'ordered', '["line","rider","taps","line_rank"]'::jsonb, '[["Blue","Adi",40,1],["Blue","Mira",40,1],["Blue","Dev",20,3],["Gold","Noor",25,1],["Gold","Tara",10,2]]'::jsonb, '[25,25,23,20]'::jsonb);

create schema fixture_r17_v20260904_1_hidden_a;
revoke all on schema fixture_r17_v20260904_1_hidden_a from public, anon, authenticated;
set search_path = fixture_r17_v20260904_1_hidden_a, pg_catalog;
CREATE TABLE "riders" ("line" text, "rider" text, "taps" integer);
INSERT INTO "riders" VALUES
('Gold-1', 'Tara', 10),
('Gold-1', 'Noor', 25),
('Blue-1', 'Dev', 20),
('Blue-1', 'Adi', 40),
('Blue-1', 'Mira', 40);
reset search_path;
revoke all on all tables in schema fixture_r17_v20260904_1_hidden_a from public, anon, authenticated;
grant usage on schema fixture_r17_v20260904_1_hidden_a to dilli_judge_executor;
grant select on all tables in schema fixture_r17_v20260904_1_hidden_a to dilli_judge_executor;
analyze fixture_r17_v20260904_1_hidden_a."riders";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (17, '2026-09-04.1-hidden_a', 'fixture_r17_v20260904_1_hidden_a', '2026-09-04.1', true, 'ordered', '["line","rider","taps","line_rank"]'::jsonb, '[["Blue-1","Adi",40,1],["Blue-1","Mira",40,1],["Blue-1","Dev",20,3],["Gold-1","Noor",25,1],["Gold-1","Tara",10,2]]'::jsonb, '[25,25,23,20]'::jsonb);

create schema fixture_r17_v20260904_1_hidden_b;
revoke all on schema fixture_r17_v20260904_1_hidden_b from public, anon, authenticated;
set search_path = fixture_r17_v20260904_1_hidden_b, pg_catalog;
CREATE TABLE "riders" ("line" text, "rider" text, "taps" integer);
INSERT INTO "riders" VALUES
('Gold-2', 'Tara', 10),
('Blue-2', 'Dev', 20),
('Blue-2', 'Adi', 40),
('Blue-2', 'Mira', 40);
reset search_path;
revoke all on all tables in schema fixture_r17_v20260904_1_hidden_b from public, anon, authenticated;
grant usage on schema fixture_r17_v20260904_1_hidden_b to dilli_judge_executor;
grant select on all tables in schema fixture_r17_v20260904_1_hidden_b to dilli_judge_executor;
analyze fixture_r17_v20260904_1_hidden_b."riders";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (17, '2026-09-04.1-hidden_b', 'fixture_r17_v20260904_1_hidden_b', '2026-09-04.1', true, 'ordered', '["line","rider","taps","line_rank"]'::jsonb, '[["Blue-2","Adi",40,1],["Blue-2","Mira",40,1],["Blue-2","Dev",20,3],["Gold-2","Tara",10,1]]'::jsonb, '[25,25,23,20]'::jsonb);

insert into game_private.questions (ruin_id, dataset_version, allowed_tables) values
        (18, '2026-09-04.1', '["readings"]'::jsonb);

insert into game_private.question_help values
        (18, '2026-09-04.1', 'The Previous Signal', 'Return `hour`, `signal`, and the previous reading''s `signal` as `prev_signal` (null for the first), ordered by `hour`.', '["A window function can look back one row in an ordered sequence.","Order the window by `hour` so the previous row is the previous hour."]'::jsonb, 'SELECT hour, signal,
       LAG(signal) OVER (ORDER BY hour) AS prev_signal
FROM readings
ORDER BY hour;');

create schema fixture_r18_v20260904_1_visible;
revoke all on schema fixture_r18_v20260904_1_visible from public, anon, authenticated;
set search_path = fixture_r18_v20260904_1_visible, pg_catalog;
CREATE TABLE "readings" ("hour" integer, "signal" integer);
INSERT INTO "readings" VALUES
(2, 30),
(0, 10),
(3, NULL),
(1, 20),
(4, 40);
reset search_path;
revoke all on all tables in schema fixture_r18_v20260904_1_visible from public, anon, authenticated;
grant usage on schema fixture_r18_v20260904_1_visible to dilli_judge_executor;
grant select on all tables in schema fixture_r18_v20260904_1_visible to dilli_judge_executor;
analyze fixture_r18_v20260904_1_visible."readings";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (18, '2026-09-04.1-visible', 'fixture_r18_v20260904_1_visible', '2026-09-04.1', false, 'ordered', '["hour","signal","prev_signal"]'::jsonb, '[[0,10,null],[1,20,10],[2,30,20],[3,null,30],[4,40,null]]'::jsonb, '[23,23,23]'::jsonb);

create schema fixture_r18_v20260904_1_hidden_a;
revoke all on schema fixture_r18_v20260904_1_hidden_a from public, anon, authenticated;
set search_path = fixture_r18_v20260904_1_hidden_a, pg_catalog;
CREATE TABLE "readings" ("hour" integer, "signal" integer);
INSERT INTO "readings" VALUES
(104, 40),
(101, 20),
(103, NULL),
(100, 10),
(102, 30);
reset search_path;
revoke all on all tables in schema fixture_r18_v20260904_1_hidden_a from public, anon, authenticated;
grant usage on schema fixture_r18_v20260904_1_hidden_a to dilli_judge_executor;
grant select on all tables in schema fixture_r18_v20260904_1_hidden_a to dilli_judge_executor;
analyze fixture_r18_v20260904_1_hidden_a."readings";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (18, '2026-09-04.1-hidden_a', 'fixture_r18_v20260904_1_hidden_a', '2026-09-04.1', true, 'ordered', '["hour","signal","prev_signal"]'::jsonb, '[[100,10,null],[101,20,10],[102,30,20],[103,null,30],[104,40,null]]'::jsonb, '[23,23,23]'::jsonb);

create schema fixture_r18_v20260904_1_hidden_b;
revoke all on schema fixture_r18_v20260904_1_hidden_b from public, anon, authenticated;
set search_path = fixture_r18_v20260904_1_hidden_b, pg_catalog;
CREATE TABLE "readings" ("hour" integer, "signal" integer);
INSERT INTO "readings" VALUES
(204, 40),
(203, NULL),
(200, 10),
(202, 30);
reset search_path;
revoke all on all tables in schema fixture_r18_v20260904_1_hidden_b from public, anon, authenticated;
grant usage on schema fixture_r18_v20260904_1_hidden_b to dilli_judge_executor;
grant select on all tables in schema fixture_r18_v20260904_1_hidden_b to dilli_judge_executor;
analyze fixture_r18_v20260904_1_hidden_b."readings";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (18, '2026-09-04.1-hidden_b', 'fixture_r18_v20260904_1_hidden_b', '2026-09-04.1', true, 'ordered', '["hour","signal","prev_signal"]'::jsonb, '[[200,10,null],[202,30,10],[203,null,30],[204,40,null]]'::jsonb, '[23,23,23]'::jsonb);

insert into game_private.questions (ruin_id, dataset_version, allowed_tables) values
        (19, '2026-09-04.1', '["wells"]'::jsonb);

insert into game_private.question_help values
        (19, '2026-09-04.1', 'Deeper than Average', 'Return `well_id` and `depth_m` for every well deeper than the average well depth. Sort by `depth_m` descending, then `well_id`.', '["Compute the average depth once, then compare each row against it.","A scalar subquery in the `WHERE` clause returns that single average."]'::jsonb, 'SELECT well_id, depth_m
FROM wells
WHERE depth_m > (SELECT avg(depth_m) FROM wells)
ORDER BY depth_m DESC, well_id;');

create schema fixture_r19_v20260904_1_visible;
revoke all on schema fixture_r19_v20260904_1_visible from public, anon, authenticated;
set search_path = fixture_r19_v20260904_1_visible, pg_catalog;
CREATE TABLE "wells" ("well_id" integer, "depth_m" numeric);
INSERT INTO "wells" VALUES
(1, 10),
(2, 20),
(3, 40),
(4, 40),
(5, NULL);
reset search_path;
revoke all on all tables in schema fixture_r19_v20260904_1_visible from public, anon, authenticated;
grant usage on schema fixture_r19_v20260904_1_visible to dilli_judge_executor;
grant select on all tables in schema fixture_r19_v20260904_1_visible to dilli_judge_executor;
analyze fixture_r19_v20260904_1_visible."wells";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (19, '2026-09-04.1-visible', 'fixture_r19_v20260904_1_visible', '2026-09-04.1', false, 'ordered', '["well_id","depth_m"]'::jsonb, '[[3,"40"],[4,"40"]]'::jsonb, '[23,1700]'::jsonb);

create schema fixture_r19_v20260904_1_hidden_a;
revoke all on schema fixture_r19_v20260904_1_hidden_a from public, anon, authenticated;
set search_path = fixture_r19_v20260904_1_hidden_a, pg_catalog;
CREATE TABLE "wells" ("well_id" integer, "depth_m" numeric);
INSERT INTO "wells" VALUES
(105, NULL),
(104, 40),
(103, 40),
(102, 20),
(101, 10);
reset search_path;
revoke all on all tables in schema fixture_r19_v20260904_1_hidden_a from public, anon, authenticated;
grant usage on schema fixture_r19_v20260904_1_hidden_a to dilli_judge_executor;
grant select on all tables in schema fixture_r19_v20260904_1_hidden_a to dilli_judge_executor;
analyze fixture_r19_v20260904_1_hidden_a."wells";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (19, '2026-09-04.1-hidden_a', 'fixture_r19_v20260904_1_hidden_a', '2026-09-04.1', true, 'ordered', '["well_id","depth_m"]'::jsonb, '[[103,"40"],[104,"40"]]'::jsonb, '[23,1700]'::jsonb);

create schema fixture_r19_v20260904_1_hidden_b;
revoke all on schema fixture_r19_v20260904_1_hidden_b from public, anon, authenticated;
set search_path = fixture_r19_v20260904_1_hidden_b, pg_catalog;
CREATE TABLE "wells" ("well_id" integer, "depth_m" numeric);
INSERT INTO "wells" VALUES
(205, NULL),
(203, 40),
(202, 20),
(201, 10);
reset search_path;
revoke all on all tables in schema fixture_r19_v20260904_1_hidden_b from public, anon, authenticated;
grant usage on schema fixture_r19_v20260904_1_hidden_b to dilli_judge_executor;
grant select on all tables in schema fixture_r19_v20260904_1_hidden_b to dilli_judge_executor;
analyze fixture_r19_v20260904_1_hidden_b."wells";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (19, '2026-09-04.1-hidden_b', 'fixture_r19_v20260904_1_hidden_b', '2026-09-04.1', true, 'ordered', '["well_id","depth_m"]'::jsonb, '[[203,"40"]]'::jsonb, '[23,1700]'::jsonb);

insert into game_private.questions (ruin_id, dataset_version, allowed_tables) values
        (20, '2026-09-04.1', '["spans","towers"]'::jsonb);

insert into game_private.question_help values
        (20, '2026-09-04.1', 'Spans and Their Towers', 'Return `tower_name` and `span_id` for each anchored span, plus unoccupied towers with null `span_id`. Sort by `tower_name`, then `span_id`. Try joins and `UNION`; equivalent queries work too.', '["First inner-join spans to their tower on the shared key.","A set operation appends the towers with no matching span; check with `NOT EXISTS`."]'::jsonb, 'SELECT t.tower_name, s.span_id
FROM towers t
JOIN spans s ON s.tower_id = t.tower_id
UNION
SELECT t.tower_name, NULL
FROM towers t
WHERE NOT EXISTS (SELECT 1 FROM spans s WHERE s.tower_id = t.tower_id)
ORDER BY tower_name, span_id;');

create schema fixture_r20_v20260904_1_visible;
revoke all on schema fixture_r20_v20260904_1_visible from public, anon, authenticated;
set search_path = fixture_r20_v20260904_1_visible, pg_catalog;
CREATE TABLE "spans" ("span_id" integer, "tower_id" integer);
INSERT INTO "spans" VALUES
(1, 1),
(2, 1),
(3, 2),
(4, NULL);
CREATE TABLE "towers" ("tower_id" integer, "tower_name" text);
INSERT INTO "towers" VALUES
(1, 'North'),
(2, 'East'),
(3, 'West');
reset search_path;
revoke all on all tables in schema fixture_r20_v20260904_1_visible from public, anon, authenticated;
grant usage on schema fixture_r20_v20260904_1_visible to dilli_judge_executor;
grant select on all tables in schema fixture_r20_v20260904_1_visible to dilli_judge_executor;
analyze fixture_r20_v20260904_1_visible."spans";
analyze fixture_r20_v20260904_1_visible."towers";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (20, '2026-09-04.1-visible', 'fixture_r20_v20260904_1_visible', '2026-09-04.1', false, 'ordered', '["tower_name","span_id"]'::jsonb, '[["East",3],["North",1],["North",2],["West",null]]'::jsonb, '[25,23]'::jsonb);

create schema fixture_r20_v20260904_1_hidden_a;
revoke all on schema fixture_r20_v20260904_1_hidden_a from public, anon, authenticated;
set search_path = fixture_r20_v20260904_1_hidden_a, pg_catalog;
CREATE TABLE "spans" ("span_id" integer, "tower_id" integer);
INSERT INTO "spans" VALUES
(104, NULL),
(103, 102),
(102, 101),
(101, 101);
CREATE TABLE "towers" ("tower_id" integer, "tower_name" text);
INSERT INTO "towers" VALUES
(103, 'West-1'),
(102, 'East-1'),
(101, 'North-1');
reset search_path;
revoke all on all tables in schema fixture_r20_v20260904_1_hidden_a from public, anon, authenticated;
grant usage on schema fixture_r20_v20260904_1_hidden_a to dilli_judge_executor;
grant select on all tables in schema fixture_r20_v20260904_1_hidden_a to dilli_judge_executor;
analyze fixture_r20_v20260904_1_hidden_a."spans";
analyze fixture_r20_v20260904_1_hidden_a."towers";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (20, '2026-09-04.1-hidden_a', 'fixture_r20_v20260904_1_hidden_a', '2026-09-04.1', true, 'ordered', '["tower_name","span_id"]'::jsonb, '[["East-1",103],["North-1",101],["North-1",102],["West-1",null]]'::jsonb, '[25,23]'::jsonb);

create schema fixture_r20_v20260904_1_hidden_b;
revoke all on schema fixture_r20_v20260904_1_hidden_b from public, anon, authenticated;
set search_path = fixture_r20_v20260904_1_hidden_b, pg_catalog;
CREATE TABLE "spans" ("span_id" integer, "tower_id" integer);
INSERT INTO "spans" VALUES
(204, NULL),
(202, 201),
(201, 201);
CREATE TABLE "towers" ("tower_id" integer, "tower_name" text);
INSERT INTO "towers" VALUES
(203, 'West-2'),
(201, 'North-2');
reset search_path;
revoke all on all tables in schema fixture_r20_v20260904_1_hidden_b from public, anon, authenticated;
grant usage on schema fixture_r20_v20260904_1_hidden_b to dilli_judge_executor;
grant select on all tables in schema fixture_r20_v20260904_1_hidden_b to dilli_judge_executor;
analyze fixture_r20_v20260904_1_hidden_b."spans";
analyze fixture_r20_v20260904_1_hidden_b."towers";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (20, '2026-09-04.1-hidden_b', 'fixture_r20_v20260904_1_hidden_b', '2026-09-04.1', true, 'ordered', '["tower_name","span_id"]'::jsonb, '[["North-2",201],["North-2",202],["West-2",null]]'::jsonb, '[25,23]'::jsonb);
