-- Generated by scripts/generate-replain-forward.mjs. Do not hand-edit computed rows.

-- Forward-only fix-up: re-applies ruins 1-5 (allowed_tables, fixtures, expected

-- rows/types, and private help incl. solution) at dataset_version 2026-09-04.1.

-- Fresh DBs already receive this from 20260904120000; the live DB does not,

-- because that version is tracked as applied and never re-runs on content change.

begin;

update game_private.questions set allowed_tables = '["record_fields"]'::jsonb where ruin_id = 1 and dataset_version = '2026-09-04.1';

update game_private.question_help set title = 'Reading the Resident Records', description = 'The `record_fields` catalogue names every record-book in the city, one field inside it, and what that field stores. List each `field` and what it `stores` for the `resident` book, in alphabetical order by `field`.', hints = '["Keep the rows where `book` = ''resident'', return `field` and `stores`, and sort by `field`."]'::jsonb, solution = 'SELECT field, stores
FROM record_fields
WHERE book = ''resident''
ORDER BY field;' where ruin_id = 1 and dataset_version = '2026-09-04.1';

delete from game_private.question_cases where ruin_id = 1 and dataset_version = '2026-09-04.1';

drop schema if exists fixture_r01_v20260904_1_visible cascade;
create schema fixture_r01_v20260904_1_visible;
revoke all on schema fixture_r01_v20260904_1_visible from public, anon, authenticated;
set search_path = fixture_r01_v20260904_1_visible, pg_catalog;
CREATE TABLE "record_fields" ("book" text, "field" text, "stores" text, "is_key" boolean);
INSERT INTO "record_fields" VALUES
('resident', 'resident_id', 'integer', true),
('resident', 'name', 'text', false),
('shelter', 'capacity', 'integer', false),
('resident', 'home_id', 'integer', false),
(NULL, 'unknown', 'text', false);
reset search_path;
revoke all on all tables in schema fixture_r01_v20260904_1_visible from public, anon, authenticated;
grant usage on schema fixture_r01_v20260904_1_visible to dilli_judge_executor;
grant select on all tables in schema fixture_r01_v20260904_1_visible to dilli_judge_executor;
analyze fixture_r01_v20260904_1_visible."record_fields";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (1, '2026-09-04.1-visible', 'fixture_r01_v20260904_1_visible', '2026-09-04.1', false, 'ordered', '["field","stores"]'::jsonb, '[["home_id","integer"],["name","text"],["resident_id","integer"]]'::jsonb, '[25,25]'::jsonb);

drop schema if exists fixture_r01_v20260904_1_hidden_a cascade;
create schema fixture_r01_v20260904_1_hidden_a;
revoke all on schema fixture_r01_v20260904_1_hidden_a from public, anon, authenticated;
set search_path = fixture_r01_v20260904_1_hidden_a, pg_catalog;
CREATE TABLE "record_fields" ("book" text, "field" text, "stores" text, "is_key" boolean);
INSERT INTO "record_fields" VALUES
(NULL, 'unknown-1', 'text', false),
('resident', 'home_id-1', 'integer', false),
('shelter', 'capacity-1', 'integer', false),
('resident', 'name-1', 'text', false),
('resident', 'resident_id-1', 'integer', true);
reset search_path;
revoke all on all tables in schema fixture_r01_v20260904_1_hidden_a from public, anon, authenticated;
grant usage on schema fixture_r01_v20260904_1_hidden_a to dilli_judge_executor;
grant select on all tables in schema fixture_r01_v20260904_1_hidden_a to dilli_judge_executor;
analyze fixture_r01_v20260904_1_hidden_a."record_fields";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (1, '2026-09-04.1-hidden_a', 'fixture_r01_v20260904_1_hidden_a', '2026-09-04.1', true, 'ordered', '["field","stores"]'::jsonb, '[["home_id-1","integer"],["name-1","text"],["resident_id-1","integer"]]'::jsonb, '[25,25]'::jsonb);

drop schema if exists fixture_r01_v20260904_1_hidden_b cascade;
create schema fixture_r01_v20260904_1_hidden_b;
revoke all on schema fixture_r01_v20260904_1_hidden_b from public, anon, authenticated;
set search_path = fixture_r01_v20260904_1_hidden_b, pg_catalog;
CREATE TABLE "record_fields" ("book" text, "field" text, "stores" text, "is_key" boolean);
INSERT INTO "record_fields" VALUES
(NULL, 'unknown-2', 'text', false),
('shelter', 'capacity-2', 'integer', false),
('resident', 'name-2', 'text', false),
('resident', 'resident_id-2', 'integer', true);
reset search_path;
revoke all on all tables in schema fixture_r01_v20260904_1_hidden_b from public, anon, authenticated;
grant usage on schema fixture_r01_v20260904_1_hidden_b to dilli_judge_executor;
grant select on all tables in schema fixture_r01_v20260904_1_hidden_b to dilli_judge_executor;
analyze fixture_r01_v20260904_1_hidden_b."record_fields";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (1, '2026-09-04.1-hidden_b', 'fixture_r01_v20260904_1_hidden_b', '2026-09-04.1', true, 'ordered', '["field","stores"]'::jsonb, '[["name-2","text"],["resident_id-2","integer"]]'::jsonb, '[25,25]'::jsonb);

update game_private.questions set allowed_tables = '["id_tags"]'::jsonb where ruin_id = 2 and dataset_version = '2026-09-04.1';

update game_private.question_help set title = 'Keys to the Bus Bay', description = 'A field''s `tag` shows if it can pick out one record alone: `''main''` is the official identifier, `''spare''` also works alone, `''none''` can''t. For the `bus` book, list every `field` tagged `''main''` or `''spare''`, alphabetically.', hints = '["Filter to `book` = ''bus'' and `tag` in (''main'', ''spare''), then sort by `field`."]'::jsonb, solution = 'SELECT field
FROM id_tags
WHERE book = ''bus''
  AND tag IN (''main'', ''spare'')
ORDER BY field;' where ruin_id = 2 and dataset_version = '2026-09-04.1';

delete from game_private.question_cases where ruin_id = 2 and dataset_version = '2026-09-04.1';

drop schema if exists fixture_r02_v20260904_1_visible cascade;
create schema fixture_r02_v20260904_1_visible;
revoke all on schema fixture_r02_v20260904_1_visible from public, anon, authenticated;
set search_path = fixture_r02_v20260904_1_visible, pg_catalog;
CREATE TABLE "id_tags" ("book" text, "field" text, "tag" text);
INSERT INTO "id_tags" VALUES
('bus', 'bus_id', 'main'),
('bus', 'registration', 'spare'),
('bus', 'radio_code', 'none'),
('bus', 'colour', 'none'),
('driver', 'licence', 'spare'),
('bus', 'unknown', NULL);
reset search_path;
revoke all on all tables in schema fixture_r02_v20260904_1_visible from public, anon, authenticated;
grant usage on schema fixture_r02_v20260904_1_visible to dilli_judge_executor;
grant select on all tables in schema fixture_r02_v20260904_1_visible to dilli_judge_executor;
analyze fixture_r02_v20260904_1_visible."id_tags";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (2, '2026-09-04.1-visible', 'fixture_r02_v20260904_1_visible', '2026-09-04.1', false, 'ordered', '["field"]'::jsonb, '[["bus_id"],["registration"]]'::jsonb, '[25]'::jsonb);

drop schema if exists fixture_r02_v20260904_1_hidden_a cascade;
create schema fixture_r02_v20260904_1_hidden_a;
revoke all on schema fixture_r02_v20260904_1_hidden_a from public, anon, authenticated;
set search_path = fixture_r02_v20260904_1_hidden_a, pg_catalog;
CREATE TABLE "id_tags" ("book" text, "field" text, "tag" text);
INSERT INTO "id_tags" VALUES
('bus', 'unknown-1', NULL),
('driver', 'licence-1', 'spare'),
('bus', 'colour-1', 'none'),
('bus', 'radio_code-1', 'none'),
('bus', 'registration-1', 'spare'),
('bus', 'bus_id-1', 'main');
reset search_path;
revoke all on all tables in schema fixture_r02_v20260904_1_hidden_a from public, anon, authenticated;
grant usage on schema fixture_r02_v20260904_1_hidden_a to dilli_judge_executor;
grant select on all tables in schema fixture_r02_v20260904_1_hidden_a to dilli_judge_executor;
analyze fixture_r02_v20260904_1_hidden_a."id_tags";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (2, '2026-09-04.1-hidden_a', 'fixture_r02_v20260904_1_hidden_a', '2026-09-04.1', true, 'ordered', '["field"]'::jsonb, '[["bus_id-1"],["registration-1"]]'::jsonb, '[25]'::jsonb);

drop schema if exists fixture_r02_v20260904_1_hidden_b cascade;
create schema fixture_r02_v20260904_1_hidden_b;
revoke all on schema fixture_r02_v20260904_1_hidden_b from public, anon, authenticated;
set search_path = fixture_r02_v20260904_1_hidden_b, pg_catalog;
CREATE TABLE "id_tags" ("book" text, "field" text, "tag" text);
INSERT INTO "id_tags" VALUES
('bus', 'unknown-2', NULL),
('bus', 'colour-2', 'none'),
('bus', 'radio_code-2', 'none'),
('bus', 'registration-2', 'spare'),
('bus', 'bus_id-2', 'main');
reset search_path;
revoke all on all tables in schema fixture_r02_v20260904_1_hidden_b from public, anon, authenticated;
grant usage on schema fixture_r02_v20260904_1_hidden_b to dilli_judge_executor;
grant select on all tables in schema fixture_r02_v20260904_1_hidden_b to dilli_judge_executor;
analyze fixture_r02_v20260904_1_hidden_b."id_tags";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (2, '2026-09-04.1-hidden_b', 'fixture_r02_v20260904_1_hidden_b', '2026-09-04.1', true, 'ordered', '["field"]'::jsonb, '[["bus_id-2"],["registration-2"]]'::jsonb, '[25]'::jsonb);

update game_private.questions set allowed_tables = '["links"]'::jsonb where ruin_id = 3 and dataset_version = '2026-09-04.1';

update game_private.question_help set title = 'Tracing the Family Links', description = 'Each row of `links` points from one record-book to another. List the `from_book` and `from_field` of every link whose `to_book` is `family`, sorted by both.', hints = '["Keep the rows where `to_book` = ''family'', then sort by `from_book`, then `from_field`."]'::jsonb, solution = 'SELECT from_book, from_field
FROM links
WHERE to_book = ''family''
ORDER BY from_book, from_field;' where ruin_id = 3 and dataset_version = '2026-09-04.1';

delete from game_private.question_cases where ruin_id = 3 and dataset_version = '2026-09-04.1';

drop schema if exists fixture_r03_v20260904_1_visible cascade;
create schema fixture_r03_v20260904_1_visible;
revoke all on schema fixture_r03_v20260904_1_visible from public, anon, authenticated;
set search_path = fixture_r03_v20260904_1_visible, pg_catalog;
CREATE TABLE "links" ("from_book" text, "from_field" text, "to_book" text, "to_field" text);
INSERT INTO "links" VALUES
('residents', 'family_id', 'family', 'id'),
('ration_cards', 'household', 'family', 'id'),
('residents', 'shelter_id', 'shelter', 'id'),
('families', 'ward', 'ward', 'id');
reset search_path;
revoke all on all tables in schema fixture_r03_v20260904_1_visible from public, anon, authenticated;
grant usage on schema fixture_r03_v20260904_1_visible to dilli_judge_executor;
grant select on all tables in schema fixture_r03_v20260904_1_visible to dilli_judge_executor;
analyze fixture_r03_v20260904_1_visible."links";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (3, '2026-09-04.1-visible', 'fixture_r03_v20260904_1_visible', '2026-09-04.1', false, 'ordered', '["from_book","from_field"]'::jsonb, '[["ration_cards","household"],["residents","family_id"]]'::jsonb, '[25,25]'::jsonb);

drop schema if exists fixture_r03_v20260904_1_hidden_a cascade;
create schema fixture_r03_v20260904_1_hidden_a;
revoke all on schema fixture_r03_v20260904_1_hidden_a from public, anon, authenticated;
set search_path = fixture_r03_v20260904_1_hidden_a, pg_catalog;
CREATE TABLE "links" ("from_book" text, "from_field" text, "to_book" text, "to_field" text);
INSERT INTO "links" VALUES
('families-1', 'ward', 'ward', 'id'),
('residents-1', 'shelter_id', 'shelter', 'id'),
('ration_cards-1', 'household', 'family', 'id'),
('residents-1', 'family_id', 'family', 'id');
reset search_path;
revoke all on all tables in schema fixture_r03_v20260904_1_hidden_a from public, anon, authenticated;
grant usage on schema fixture_r03_v20260904_1_hidden_a to dilli_judge_executor;
grant select on all tables in schema fixture_r03_v20260904_1_hidden_a to dilli_judge_executor;
analyze fixture_r03_v20260904_1_hidden_a."links";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (3, '2026-09-04.1-hidden_a', 'fixture_r03_v20260904_1_hidden_a', '2026-09-04.1', true, 'ordered', '["from_book","from_field"]'::jsonb, '[["ration_cards-1","household"],["residents-1","family_id"]]'::jsonb, '[25,25]'::jsonb);

drop schema if exists fixture_r03_v20260904_1_hidden_b cascade;
create schema fixture_r03_v20260904_1_hidden_b;
revoke all on schema fixture_r03_v20260904_1_hidden_b from public, anon, authenticated;
set search_path = fixture_r03_v20260904_1_hidden_b, pg_catalog;
CREATE TABLE "links" ("from_book" text, "from_field" text, "to_book" text, "to_field" text);
INSERT INTO "links" VALUES
('families-2', 'ward', 'ward', 'id'),
('ration_cards-2', 'household', 'family', 'id'),
('residents-2', 'family_id', 'family', 'id');
reset search_path;
revoke all on all tables in schema fixture_r03_v20260904_1_hidden_b from public, anon, authenticated;
grant usage on schema fixture_r03_v20260904_1_hidden_b to dilli_judge_executor;
grant select on all tables in schema fixture_r03_v20260904_1_hidden_b to dilli_judge_executor;
analyze fixture_r03_v20260904_1_hidden_b."links";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (3, '2026-09-04.1-hidden_b', 'fixture_r03_v20260904_1_hidden_b', '2026-09-04.1', true, 'ordered', '["from_book","from_field"]'::jsonb, '[["ration_cards-2","household"],["residents-2","family_id"]]'::jsonb, '[25,25]'::jsonb);

update game_private.questions set allowed_tables = '["change_log"]'::jsonb where ruin_id = 4 and dataset_version = '2026-09-04.1';

update game_private.question_help set title = 'Evidence of the Rebuild', description = 'The `change_log` records every edit to the archives — some change a book''s structure, others its contents. Show the `target` and `edit` for rows whose `change_type` is `structure`, newest `changed_at` first.', hints = '["Keep the rows where `change_type` = ''structure'', then order by `changed_at` from newest to oldest."]'::jsonb, solution = 'SELECT target, edit
FROM change_log
WHERE change_type = ''structure''
ORDER BY changed_at DESC;' where ruin_id = 4 and dataset_version = '2026-09-04.1';

delete from game_private.question_cases where ruin_id = 4 and dataset_version = '2026-09-04.1';

drop schema if exists fixture_r04_v20260904_1_visible cascade;
create schema fixture_r04_v20260904_1_visible;
revoke all on schema fixture_r04_v20260904_1_visible from public, anon, authenticated;
set search_path = fixture_r04_v20260904_1_visible, pg_catalog;
CREATE TABLE "change_log" ("edit" text, "target" text, "change_type" text, "changed_at" timestamp);
INSERT INTO "change_log" VALUES
('built the book', 'shelters', 'structure', '2042-01-02 10:00:00'),
('added records', 'residents', 'contents', '2042-01-04 10:00:00'),
('renamed a field', 'pumps', 'structure', '2042-01-03 10:00:00'),
('edited records', 'pumps', 'contents', NULL);
reset search_path;
revoke all on all tables in schema fixture_r04_v20260904_1_visible from public, anon, authenticated;
grant usage on schema fixture_r04_v20260904_1_visible to dilli_judge_executor;
grant select on all tables in schema fixture_r04_v20260904_1_visible to dilli_judge_executor;
analyze fixture_r04_v20260904_1_visible."change_log";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (4, '2026-09-04.1-visible', 'fixture_r04_v20260904_1_visible', '2026-09-04.1', false, 'ordered', '["target","edit"]'::jsonb, '[["pumps","renamed a field"],["shelters","built the book"]]'::jsonb, '[25,25]'::jsonb);

drop schema if exists fixture_r04_v20260904_1_hidden_a cascade;
create schema fixture_r04_v20260904_1_hidden_a;
revoke all on schema fixture_r04_v20260904_1_hidden_a from public, anon, authenticated;
set search_path = fixture_r04_v20260904_1_hidden_a, pg_catalog;
CREATE TABLE "change_log" ("edit" text, "target" text, "change_type" text, "changed_at" timestamp);
INSERT INTO "change_log" VALUES
('edited records', 'pumps-1', 'contents', NULL),
('renamed a field', 'pumps-1', 'structure', '2042-01-03 10:00:00'),
('added records', 'residents-1', 'contents', '2042-01-04 10:00:00'),
('built the book', 'shelters-1', 'structure', '2042-01-02 10:00:00');
reset search_path;
revoke all on all tables in schema fixture_r04_v20260904_1_hidden_a from public, anon, authenticated;
grant usage on schema fixture_r04_v20260904_1_hidden_a to dilli_judge_executor;
grant select on all tables in schema fixture_r04_v20260904_1_hidden_a to dilli_judge_executor;
analyze fixture_r04_v20260904_1_hidden_a."change_log";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (4, '2026-09-04.1-hidden_a', 'fixture_r04_v20260904_1_hidden_a', '2026-09-04.1', true, 'ordered', '["target","edit"]'::jsonb, '[["pumps-1","renamed a field"],["shelters-1","built the book"]]'::jsonb, '[25,25]'::jsonb);

drop schema if exists fixture_r04_v20260904_1_hidden_b cascade;
create schema fixture_r04_v20260904_1_hidden_b;
revoke all on schema fixture_r04_v20260904_1_hidden_b from public, anon, authenticated;
set search_path = fixture_r04_v20260904_1_hidden_b, pg_catalog;
CREATE TABLE "change_log" ("edit" text, "target" text, "change_type" text, "changed_at" timestamp);
INSERT INTO "change_log" VALUES
('edited records', 'pumps-2', 'contents', NULL),
('added records', 'residents-2', 'contents', '2042-01-04 10:00:00'),
('built the book', 'shelters-2', 'structure', '2042-01-02 10:00:00');
reset search_path;
revoke all on all tables in schema fixture_r04_v20260904_1_hidden_b from public, anon, authenticated;
grant usage on schema fixture_r04_v20260904_1_hidden_b to dilli_judge_executor;
grant select on all tables in schema fixture_r04_v20260904_1_hidden_b to dilli_judge_executor;
analyze fixture_r04_v20260904_1_hidden_b."change_log";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (4, '2026-09-04.1-hidden_b', 'fixture_r04_v20260904_1_hidden_b', '2026-09-04.1', true, 'ordered', '["target","edit"]'::jsonb, '[["shelters-2","built the book"]]'::jsonb, '[25,25]'::jsonb);

update game_private.questions set allowed_tables = '["permissions"]'::jsonb where ruin_id = 5 and dataset_version = '2026-09-04.1';

update game_private.question_help set title = 'Who Holds the Keys', description = 'The `permissions` book records who may do what to each record-book. Show the `who` and `record_book` for every row where the `action` is `''read''` and it is `allowed`, sorted by both.', hints = '["Keep rows where `action` = ''read'' and `allowed` is true, then sort by `who`, then `record_book`."]'::jsonb, solution = 'SELECT who, record_book
FROM permissions
WHERE action = ''read''
  AND allowed
ORDER BY who, record_book;' where ruin_id = 5 and dataset_version = '2026-09-04.1';

delete from game_private.question_cases where ruin_id = 5 and dataset_version = '2026-09-04.1';

drop schema if exists fixture_r05_v20260904_1_visible cascade;
create schema fixture_r05_v20260904_1_visible;
revoke all on schema fixture_r05_v20260904_1_visible from public, anon, authenticated;
set search_path = fixture_r05_v20260904_1_visible, pg_catalog;
CREATE TABLE "permissions" ("who" text, "record_book" text, "action" text, "allowed" boolean);
INSERT INTO "permissions" VALUES
('scout', 'shelters', 'read', true),
('archivist', 'records', 'read', true),
('archivist', 'maps', 'read', true),
('porter', 'crates', 'read', false),
('builder', 'repairs', 'write', true),
('unknown', 'maps', 'read', NULL);
reset search_path;
revoke all on all tables in schema fixture_r05_v20260904_1_visible from public, anon, authenticated;
grant usage on schema fixture_r05_v20260904_1_visible to dilli_judge_executor;
grant select on all tables in schema fixture_r05_v20260904_1_visible to dilli_judge_executor;
analyze fixture_r05_v20260904_1_visible."permissions";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (5, '2026-09-04.1-visible', 'fixture_r05_v20260904_1_visible', '2026-09-04.1', false, 'ordered', '["who","record_book"]'::jsonb, '[["archivist","maps"],["archivist","records"],["scout","shelters"]]'::jsonb, '[25,25]'::jsonb);

drop schema if exists fixture_r05_v20260904_1_hidden_a cascade;
create schema fixture_r05_v20260904_1_hidden_a;
revoke all on schema fixture_r05_v20260904_1_hidden_a from public, anon, authenticated;
set search_path = fixture_r05_v20260904_1_hidden_a, pg_catalog;
CREATE TABLE "permissions" ("who" text, "record_book" text, "action" text, "allowed" boolean);
INSERT INTO "permissions" VALUES
('unknown-1', 'maps', 'read', NULL),
('builder-1', 'repairs', 'write', true),
('porter-1', 'crates', 'read', false),
('archivist-1', 'maps', 'read', true),
('archivist-1', 'records', 'read', true),
('scout-1', 'shelters', 'read', true);
reset search_path;
revoke all on all tables in schema fixture_r05_v20260904_1_hidden_a from public, anon, authenticated;
grant usage on schema fixture_r05_v20260904_1_hidden_a to dilli_judge_executor;
grant select on all tables in schema fixture_r05_v20260904_1_hidden_a to dilli_judge_executor;
analyze fixture_r05_v20260904_1_hidden_a."permissions";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (5, '2026-09-04.1-hidden_a', 'fixture_r05_v20260904_1_hidden_a', '2026-09-04.1', true, 'ordered', '["who","record_book"]'::jsonb, '[["archivist-1","maps"],["archivist-1","records"],["scout-1","shelters"]]'::jsonb, '[25,25]'::jsonb);

drop schema if exists fixture_r05_v20260904_1_hidden_b cascade;
create schema fixture_r05_v20260904_1_hidden_b;
revoke all on schema fixture_r05_v20260904_1_hidden_b from public, anon, authenticated;
set search_path = fixture_r05_v20260904_1_hidden_b, pg_catalog;
CREATE TABLE "permissions" ("who" text, "record_book" text, "action" text, "allowed" boolean);
INSERT INTO "permissions" VALUES
('unknown-2', 'maps', 'read', NULL),
('porter-2', 'crates', 'read', false),
('archivist-2', 'maps', 'read', true),
('archivist-2', 'records', 'read', true),
('scout-2', 'shelters', 'read', true);
reset search_path;
revoke all on all tables in schema fixture_r05_v20260904_1_hidden_b from public, anon, authenticated;
grant usage on schema fixture_r05_v20260904_1_hidden_b to dilli_judge_executor;
grant select on all tables in schema fixture_r05_v20260904_1_hidden_b to dilli_judge_executor;
analyze fixture_r05_v20260904_1_hidden_b."permissions";
insert into game_private.question_cases
(ruin_id, case_id, fixture_schema, dataset_version, hidden, comparison, expected_columns, expected_rows, expected_types)
values (5, '2026-09-04.1-hidden_b', 'fixture_r05_v20260904_1_hidden_b', '2026-09-04.1', true, 'ordered', '["who","record_book"]'::jsonb, '[["archivist-2","maps"],["archivist-2","records"],["scout-2","shelters"]]'::jsonb, '[25,25]'::jsonb);

commit;
